class TimeZoneItem {
  final String timezone;
  final String location;
  final String countryCode;
  final String flag;

  const TimeZoneItem({
    required this.timezone,
    required this.location,
    required this.countryCode,
    required this.flag,
  });
}

const List<TimeZoneItem> timeZones = [
  TimeZoneItem(
    timezone: 'Africa/Abidjan',
    location: 'Abidjan',
    countryCode: 'ci',
    flag: 'https://flagcdn.com/w80/ci.png',
  ),
  TimeZoneItem(
    timezone: 'Africa/Accra',
    location: 'Accra',
    countryCode: 'gh',
    flag: 'https://flagcdn.com/w80/gh.png',
  ),
  TimeZoneItem(
    timezone: 'Africa/Addis_Ababa',
    location: 'Addis Ababa',
    countryCode: 'et',
    flag: 'https://flagcdn.com/w80/et.png',
  ),
  TimeZoneItem(
    timezone: 'Africa/Algiers',
    location: 'Algiers',
    countryCode: 'dz',
    flag: 'https://flagcdn.com/w80/dz.png',
  ),
  TimeZoneItem(
    timezone: 'Africa/Asmara',
    location: 'Asmara',
    countryCode: 'er',
    flag: 'https://flagcdn.com/w80/er.png',
  ),
  TimeZoneItem(
    timezone: 'Africa/Bamako',
    location: 'Bamako',
    countryCode: 'ml',
    flag: 'https://flagcdn.com/w80/ml.png',
  ),
  TimeZoneItem(
    timezone: 'Africa/Bangui',
    location: 'Bangui',
    countryCode: 'cf',
    flag: 'https://flagcdn.com/w80/cf.png',
  ),
  TimeZoneItem(
    timezone: 'Africa/Banjul',
    location: 'Banjul',
    countryCode: 'gm',
    flag: 'https://flagcdn.com/w80/gm.png',
  ),
  TimeZoneItem(
    timezone: 'Africa/Bissau',
    location: 'Bissau',
    countryCode: 'gw',
    flag: 'https://flagcdn.com/w80/gw.png',
  ),
  TimeZoneItem(
    timezone: 'Africa/Blantyre',
    location: 'Blantyre',
    countryCode: 'mw',
    flag: 'https://flagcdn.com/w80/mw.png',
  ),
  TimeZoneItem(
    timezone: 'Africa/Brazzaville',
    location: 'Brazzaville',
    countryCode: 'cg',
    flag: 'https://flagcdn.com/w80/cg.png',
  ),
  TimeZoneItem(
    timezone: 'Africa/Bujumbura',
    location: 'Bujumbura',
    countryCode: 'bi',
    flag: 'https://flagcdn.com/w80/bi.png',
  ),
  TimeZoneItem(
    timezone: 'Africa/Cairo',
    location: 'Cairo',
    countryCode: 'eg',
    flag: 'https://flagcdn.com/w80/eg.png',
  ),
  TimeZoneItem(
    timezone: 'Africa/Casablanca',
    location: 'Casablanca',
    countryCode: 'ma',
    flag: 'https://flagcdn.com/w80/ma.png',
  ),
  TimeZoneItem(
    timezone: 'Africa/Ceuta',
    location: 'Ceuta',
    countryCode: 'es',
    flag: 'https://flagcdn.com/w80/es.png',
  ),
  TimeZoneItem(
    timezone: 'Africa/Conakry',
    location: 'Conakry',
    countryCode: 'gn',
    flag: 'https://flagcdn.com/w80/gn.png',
  ),
  TimeZoneItem(
    timezone: 'Africa/Dakar',
    location: 'Dakar',
    countryCode: 'sn',
    flag: 'https://flagcdn.com/w80/sn.png',
  ),
  TimeZoneItem(
    timezone: 'Africa/Dar_es_Salaam',
    location: 'Dar es Salaam',
    countryCode: 'tz',
    flag: 'https://flagcdn.com/w80/tz.png',
  ),
  TimeZoneItem(
    timezone: 'Africa/Djibouti',
    location: 'Djibouti',
    countryCode: 'dj',
    flag: 'https://flagcdn.com/w80/dj.png',
  ),
  TimeZoneItem(
    timezone: 'Africa/Douala',
    location: 'Douala',
    countryCode: 'cm',
    flag: 'https://flagcdn.com/w80/cm.png',
  ),
  TimeZoneItem(
    timezone: 'Africa/El_Aaiun',
    location: 'El Aaiun',
    countryCode: 'eh',
    flag: 'https://flagcdn.com/w80/eh.png',
  ),
  TimeZoneItem(
    timezone: 'Africa/Freetown',
    location: 'Freetown',
    countryCode: 'sl',
    flag: 'https://flagcdn.com/w80/sl.png',
  ),
  TimeZoneItem(
    timezone: 'Africa/Gaborone',
    location: 'Gaborone',
    countryCode: 'bw',
    flag: 'https://flagcdn.com/w80/bw.png',
  ),
  TimeZoneItem(
    timezone: 'Africa/Harare',
    location: 'Harare',
    countryCode: 'zw',
    flag: 'https://flagcdn.com/w80/zw.png',
  ),
  TimeZoneItem(
    timezone: 'Africa/Johannesburg',
    location: 'Johannesburg',
    countryCode: 'za',
    flag: 'https://flagcdn.com/w80/za.png',
  ),
  TimeZoneItem(
    timezone: 'Africa/Juba',
    location: 'Juba',
    countryCode: 'ss',
    flag: 'https://flagcdn.com/w80/ss.png',
  ),
  TimeZoneItem(
    timezone: 'Africa/Kampala',
    location: 'Kampala',
    countryCode: 'ug',
    flag: 'https://flagcdn.com/w80/ug.png',
  ),
  TimeZoneItem(
    timezone: 'Africa/Khartoum',
    location: 'Khartoum',
    countryCode: 'sd',
    flag: 'https://flagcdn.com/w80/sd.png',
  ),
  TimeZoneItem(
    timezone: 'Africa/Kigali',
    location: 'Kigali',
    countryCode: 'rw',
    flag: 'https://flagcdn.com/w80/rw.png',
  ),
  TimeZoneItem(
    timezone: 'Africa/Kinshasa',
    location: 'Kinshasa',
    countryCode: 'cd',
    flag: 'https://flagcdn.com/w80/cd.png',
  ),
  TimeZoneItem(
    timezone: 'Africa/Lagos',
    location: 'Lagos',
    countryCode: 'ng',
    flag: 'https://flagcdn.com/w80/ng.png',
  ),
  TimeZoneItem(
    timezone: 'Africa/Libreville',
    location: 'Libreville',
    countryCode: 'ga',
    flag: 'https://flagcdn.com/w80/ga.png',
  ),
  TimeZoneItem(
    timezone: 'Africa/Lome',
    location: 'Lome',
    countryCode: 'tg',
    flag: 'https://flagcdn.com/w80/tg.png',
  ),
  TimeZoneItem(
    timezone: 'Africa/Luanda',
    location: 'Luanda',
    countryCode: 'ao',
    flag: 'https://flagcdn.com/w80/ao.png',
  ),
  TimeZoneItem(
    timezone: 'Africa/Lubumbashi',
    location: 'Lubumbashi',
    countryCode: 'cd',
    flag: 'https://flagcdn.com/w80/cd.png',
  ),
  TimeZoneItem(
    timezone: 'Africa/Lusaka',
    location: 'Lusaka',
    countryCode: 'zm',
    flag: 'https://flagcdn.com/w80/zm.png',
  ),
  TimeZoneItem(
    timezone: 'Africa/Malabo',
    location: 'Malabo',
    countryCode: 'gq',
    flag: 'https://flagcdn.com/w80/gq.png',
  ),
  TimeZoneItem(
    timezone: 'Africa/Maputo',
    location: 'Maputo',
    countryCode: 'mz',
    flag: 'https://flagcdn.com/w80/mz.png',
  ),
  TimeZoneItem(
    timezone: 'Africa/Maseru',
    location: 'Maseru',
    countryCode: 'ls',
    flag: 'https://flagcdn.com/w80/ls.png',
  ),
  TimeZoneItem(
    timezone: 'Africa/Mbabane',
    location: 'Mbabane',
    countryCode: 'sz',
    flag: 'https://flagcdn.com/w80/sz.png',
  ),
  TimeZoneItem(
    timezone: 'Africa/Mogadishu',
    location: 'Mogadishu',
    countryCode: 'so',
    flag: 'https://flagcdn.com/w80/so.png',
  ),
  TimeZoneItem(
    timezone: 'Africa/Monrovia',
    location: 'Monrovia',
    countryCode: 'lr',
    flag: 'https://flagcdn.com/w80/lr.png',
  ),
  TimeZoneItem(
    timezone: 'Africa/Nairobi',
    location: 'Nairobi',
    countryCode: 'ke',
    flag: 'https://flagcdn.com/w80/ke.png',
  ),
  TimeZoneItem(
    timezone: 'Africa/Ndjamena',
    location: 'Ndjamena',
    countryCode: 'td',
    flag: 'https://flagcdn.com/w80/td.png',
  ),
  TimeZoneItem(
    timezone: 'Africa/Niamey',
    location: 'Niamey',
    countryCode: 'ne',
    flag: 'https://flagcdn.com/w80/ne.png',
  ),
  TimeZoneItem(
    timezone: 'Africa/Nouakchott',
    location: 'Nouakchott',
    countryCode: 'mr',
    flag: 'https://flagcdn.com/w80/mr.png',
  ),
  TimeZoneItem(
    timezone: 'Africa/Ouagadougou',
    location: 'Ouagadougou',
    countryCode: 'bf',
    flag: 'https://flagcdn.com/w80/bf.png',
  ),
  TimeZoneItem(
    timezone: 'Africa/Porto-Novo',
    location: 'Porto-Novo',
    countryCode: 'bj',
    flag: 'https://flagcdn.com/w80/bj.png',
  ),
  TimeZoneItem(
    timezone: 'Africa/Sao_Tome',
    location: 'Sao Tome',
    countryCode: 'st',
    flag: 'https://flagcdn.com/w80/st.png',
  ),
  TimeZoneItem(
    timezone: 'Africa/Timbuktu',
    location: 'Timbuktu',
    countryCode: 'ml',
    flag: 'https://flagcdn.com/w80/ml.png',
  ),
  TimeZoneItem(
    timezone: 'Africa/Tripoli',
    location: 'Tripoli',
    countryCode: 'ly',
    flag: 'https://flagcdn.com/w80/ly.png',
  ),
  TimeZoneItem(
    timezone: 'Africa/Tunis',
    location: 'Tunis',
    countryCode: 'tn',
    flag: 'https://flagcdn.com/w80/tn.png',
  ),
  TimeZoneItem(
    timezone: 'Africa/Windhoek',
    location: 'Windhoek',
    countryCode: 'na',
    flag: 'https://flagcdn.com/w80/na.png',
  ),
  TimeZoneItem(
    timezone: 'America/Adak',
    location: 'Adak',
    countryCode: 'us',
    flag: 'https://flagcdn.com/w80/us.png',
  ),
  TimeZoneItem(
    timezone: 'America/Anchorage',
    location: 'Anchorage',
    countryCode: 'us',
    flag: 'https://flagcdn.com/w80/us.png',
  ),
  TimeZoneItem(
    timezone: 'America/Anguilla',
    location: 'Anguilla',
    countryCode: 'ai',
    flag: 'https://flagcdn.com/w80/ai.png',
  ),
  TimeZoneItem(
    timezone: 'America/Antigua',
    location: 'Antigua',
    countryCode: 'ag',
    flag: 'https://flagcdn.com/w80/ag.png',
  ),
  TimeZoneItem(
    timezone: 'America/Araguaina',
    location: 'Araguaina',
    countryCode: 'br',
    flag: 'https://flagcdn.com/w80/br.png',
  ),
  TimeZoneItem(
    timezone: 'America/Argentina/Buenos_Aires',
    location: 'Buenos Aires',
    countryCode: 'ar',
    flag: 'https://flagcdn.com/w80/ar.png',
  ),
  TimeZoneItem(
    timezone: 'America/Argentina/Catamarca',
    location: 'Catamarca',
    countryCode: 'ar',
    flag: 'https://flagcdn.com/w80/ar.png',
  ),
  TimeZoneItem(
    timezone: 'America/Argentina/ComodRivadavia',
    location: 'ComodRivadavia',
    countryCode: 'ar',
    flag: 'https://flagcdn.com/w80/ar.png',
  ),
  TimeZoneItem(
    timezone: 'America/Argentina/Cordoba',
    location: 'Cordoba',
    countryCode: 'ar',
    flag: 'https://flagcdn.com/w80/ar.png',
  ),
  TimeZoneItem(
    timezone: 'America/Argentina/Jujuy',
    location: 'Jujuy',
    countryCode: 'ar',
    flag: 'https://flagcdn.com/w80/ar.png',
  ),
  TimeZoneItem(
    timezone: 'America/Argentina/La_Rioja',
    location: 'La Rioja',
    countryCode: 'ar',
    flag: 'https://flagcdn.com/w80/ar.png',
  ),
  TimeZoneItem(
    timezone: 'America/Argentina/Mendoza',
    location: 'Mendoza',
    countryCode: 'ar',
    flag: 'https://flagcdn.com/w80/ar.png',
  ),
  TimeZoneItem(
    timezone: 'America/Argentina/Rio_Gallegos',
    location: 'Rio Gallegos',
    countryCode: 'ar',
    flag: 'https://flagcdn.com/w80/ar.png',
  ),
  TimeZoneItem(
    timezone: 'America/Argentina/Salta',
    location: 'Salta',
    countryCode: 'ar',
    flag: 'https://flagcdn.com/w80/ar.png',
  ),
  TimeZoneItem(
    timezone: 'America/Argentina/San_Juan',
    location: 'San Juan',
    countryCode: 'ar',
    flag: 'https://flagcdn.com/w80/ar.png',
  ),
  TimeZoneItem(
    timezone: 'America/Argentina/San_Luis',
    location: 'San Luis',
    countryCode: 'ar',
    flag: 'https://flagcdn.com/w80/ar.png',
  ),
  TimeZoneItem(
    timezone: 'America/Argentina/Tucuman',
    location: 'Tucuman',
    countryCode: 'ar',
    flag: 'https://flagcdn.com/w80/ar.png',
  ),
  TimeZoneItem(
    timezone: 'America/Argentina/Ushuaia',
    location: 'Ushuaia',
    countryCode: 'ar',
    flag: 'https://flagcdn.com/w80/ar.png',
  ),
  TimeZoneItem(
    timezone: 'America/Aruba',
    location: 'Aruba',
    countryCode: 'aw',
    flag: 'https://flagcdn.com/w80/aw.png',
  ),
  TimeZoneItem(
    timezone: 'America/Asuncion',
    location: 'Asuncion',
    countryCode: 'py',
    flag: 'https://flagcdn.com/w80/py.png',
  ),
  TimeZoneItem(
    timezone: 'America/Atikokan',
    location: 'Atikokan',
    countryCode: 'ca',
    flag: 'https://flagcdn.com/w80/ca.png',
  ),
  TimeZoneItem(
    timezone: 'America/Atka',
    location: 'Atka',
    countryCode: 'us',
    flag: 'https://flagcdn.com/w80/us.png',
  ),
  TimeZoneItem(
    timezone: 'America/Bahia',
    location: 'Bahia',
    countryCode: 'br',
    flag: 'https://flagcdn.com/w80/br.png',
  ),
  TimeZoneItem(
    timezone: 'America/Bahia_Banderas',
    location: 'Bahia Banderas',
    countryCode: 'mx',
    flag: 'https://flagcdn.com/w80/mx.png',
  ),
  TimeZoneItem(
    timezone: 'America/Barbados',
    location: 'Barbados',
    countryCode: 'bb',
    flag: 'https://flagcdn.com/w80/bb.png',
  ),
  TimeZoneItem(
    timezone: 'America/Belem',
    location: 'Belem',
    countryCode: 'br',
    flag: 'https://flagcdn.com/w80/br.png',
  ),
  TimeZoneItem(
    timezone: 'America/Belize',
    location: 'Belize',
    countryCode: 'bz',
    flag: 'https://flagcdn.com/w80/bz.png',
  ),
  TimeZoneItem(
    timezone: 'America/Blanc-Sablon',
    location: 'Blanc-Sablon',
    countryCode: 'ca',
    flag: 'https://flagcdn.com/w80/ca.png',
  ),
  TimeZoneItem(
    timezone: 'America/Boa_Vista',
    location: 'Boa Vista',
    countryCode: 'br',
    flag: 'https://flagcdn.com/w80/br.png',
  ),
  TimeZoneItem(
    timezone: 'America/Bogota',
    location: 'Bogota',
    countryCode: 'co',
    flag: 'https://flagcdn.com/w80/co.png',
  ),
  TimeZoneItem(
    timezone: 'America/Boise',
    location: 'Boise',
    countryCode: 'us',
    flag: 'https://flagcdn.com/w80/us.png',
  ),
  TimeZoneItem(
    timezone: 'America/Buenos_Aires',
    location: 'Buenos Aires',
    countryCode: 'ar',
    flag: 'https://flagcdn.com/w80/ar.png',
  ),
  TimeZoneItem(
    timezone: 'America/Cambridge_Bay',
    location: 'Cambridge Bay',
    countryCode: 'ca',
    flag: 'https://flagcdn.com/w80/ca.png',
  ),
  TimeZoneItem(
    timezone: 'America/Campo_Grande',
    location: 'Campo Grande',
    countryCode: 'br',
    flag: 'https://flagcdn.com/w80/br.png',
  ),
  TimeZoneItem(
    timezone: 'America/Cancun',
    location: 'Cancun',
    countryCode: 'mx',
    flag: 'https://flagcdn.com/w80/mx.png',
  ),
  TimeZoneItem(
    timezone: 'America/Caracas',
    location: 'Caracas',
    countryCode: 've',
    flag: 'https://flagcdn.com/w80/ve.png',
  ),
  TimeZoneItem(
    timezone: 'America/Catamarca',
    location: 'Catamarca',
    countryCode: 'ar',
    flag: 'https://flagcdn.com/w80/ar.png',
  ),
  TimeZoneItem(
    timezone: 'America/Cayenne',
    location: 'Cayenne',
    countryCode: 'gf',
    flag: 'https://flagcdn.com/w80/gf.png',
  ),
  TimeZoneItem(
    timezone: 'America/Cayman',
    location: 'Cayman',
    countryCode: 'ky',
    flag: 'https://flagcdn.com/w80/ky.png',
  ),
  TimeZoneItem(
    timezone: 'America/Chicago',
    location: 'Chicago',
    countryCode: 'us',
    flag: 'https://flagcdn.com/w80/us.png',
  ),
  TimeZoneItem(
    timezone: 'America/Chihuahua',
    location: 'Chihuahua',
    countryCode: 'mx',
    flag: 'https://flagcdn.com/w80/mx.png',
  ),
  TimeZoneItem(
    timezone: 'America/Ciudad_Juarez',
    location: 'Ciudad Juarez',
    countryCode: 'mx',
    flag: 'https://flagcdn.com/w80/mx.png',
  ),
  TimeZoneItem(
    timezone: 'America/Coral_Harbour',
    location: 'Coral Harbour',
    countryCode: 'ca',
    flag: 'https://flagcdn.com/w80/ca.png',
  ),
  TimeZoneItem(
    timezone: 'America/Cordoba',
    location: 'Cordoba',
    countryCode: 'ar',
    flag: 'https://flagcdn.com/w80/ar.png',
  ),
  TimeZoneItem(
    timezone: 'America/Costa_Rica',
    location: 'Costa Rica',
    countryCode: 'cr',
    flag: 'https://flagcdn.com/w80/cr.png',
  ),
  TimeZoneItem(
    timezone: 'America/Coyhaique',
    location: 'Coyhaique',
    countryCode: 'cl',
    flag: 'https://flagcdn.com/w80/cl.png',
  ),
  TimeZoneItem(
    timezone: 'America/Creston',
    location: 'Creston',
    countryCode: 'ca',
    flag: 'https://flagcdn.com/w80/ca.png',
  ),
  TimeZoneItem(
    timezone: 'America/Cuiaba',
    location: 'Cuiaba',
    countryCode: 'br',
    flag: 'https://flagcdn.com/w80/br.png',
  ),
  TimeZoneItem(
    timezone: 'America/Curacao',
    location: 'Curacao',
    countryCode: 'cw',
    flag: 'https://flagcdn.com/w80/cw.png',
  ),
  TimeZoneItem(
    timezone: 'America/Danmarkshavn',
    location: 'Danmarkshavn',
    countryCode: 'gl',
    flag: 'https://flagcdn.com/w80/gl.png',
  ),
  TimeZoneItem(
    timezone: 'America/Dawson',
    location: 'Dawson',
    countryCode: 'ca',
    flag: 'https://flagcdn.com/w80/ca.png',
  ),
  TimeZoneItem(
    timezone: 'America/Dawson_Creek',
    location: 'Dawson Creek',
    countryCode: 'ca',
    flag: 'https://flagcdn.com/w80/ca.png',
  ),
  TimeZoneItem(
    timezone: 'America/Denver',
    location: 'Denver',
    countryCode: 'us',
    flag: 'https://flagcdn.com/w80/us.png',
  ),
  TimeZoneItem(
    timezone: 'America/Detroit',
    location: 'Detroit',
    countryCode: 'us',
    flag: 'https://flagcdn.com/w80/us.png',
  ),
  TimeZoneItem(
    timezone: 'America/Dominica',
    location: 'Dominica',
    countryCode: 'dm',
    flag: 'https://flagcdn.com/w80/dm.png',
  ),
  TimeZoneItem(
    timezone: 'America/Edmonton',
    location: 'Edmonton',
    countryCode: 'ca',
    flag: 'https://flagcdn.com/w80/ca.png',
  ),
  TimeZoneItem(
    timezone: 'America/Eirunepe',
    location: 'Eirunepe',
    countryCode: 'br',
    flag: 'https://flagcdn.com/w80/br.png',
  ),
  TimeZoneItem(
    timezone: 'America/El_Salvador',
    location: 'El Salvador',
    countryCode: 'sv',
    flag: 'https://flagcdn.com/w80/sv.png',
  ),
  TimeZoneItem(
    timezone: 'America/Ensenada',
    location: 'Ensenada',
    countryCode: 'mx',
    flag: 'https://flagcdn.com/w80/mx.png',
  ),
  TimeZoneItem(
    timezone: 'America/Fort_Nelson',
    location: 'Fort Nelson',
    countryCode: 'ca',
    flag: 'https://flagcdn.com/w80/ca.png',
  ),
  TimeZoneItem(
    timezone: 'America/Fort_Wayne',
    location: 'Fort Wayne',
    countryCode: 'us',
    flag: 'https://flagcdn.com/w80/us.png',
  ),
  TimeZoneItem(
    timezone: 'America/Fortaleza',
    location: 'Fortaleza',
    countryCode: 'br',
    flag: 'https://flagcdn.com/w80/br.png',
  ),
  TimeZoneItem(
    timezone: 'America/Glace_Bay',
    location: 'Glace Bay',
    countryCode: 'ca',
    flag: 'https://flagcdn.com/w80/ca.png',
  ),
  TimeZoneItem(
    timezone: 'America/Godthab',
    location: 'Godthab',
    countryCode: 'gl',
    flag: 'https://flagcdn.com/w80/gl.png',
  ),
  TimeZoneItem(
    timezone: 'America/Goose_Bay',
    location: 'Goose Bay',
    countryCode: 'ca',
    flag: 'https://flagcdn.com/w80/ca.png',
  ),
  TimeZoneItem(
    timezone: 'America/Grand_Turk',
    location: 'Grand Turk',
    countryCode: 'tc',
    flag: 'https://flagcdn.com/w80/tc.png',
  ),
  TimeZoneItem(
    timezone: 'America/Grenada',
    location: 'Grenada',
    countryCode: 'gd',
    flag: 'https://flagcdn.com/w80/gd.png',
  ),
  TimeZoneItem(
    timezone: 'America/Guadeloupe',
    location: 'Guadeloupe',
    countryCode: 'gp',
    flag: 'https://flagcdn.com/w80/gp.png',
  ),
  TimeZoneItem(
    timezone: 'America/Guatemala',
    location: 'Guatemala',
    countryCode: 'gt',
    flag: 'https://flagcdn.com/w80/gt.png',
  ),
  TimeZoneItem(
    timezone: 'America/Guayaquil',
    location: 'Guayaquil',
    countryCode: 'ec',
    flag: 'https://flagcdn.com/w80/ec.png',
  ),
  TimeZoneItem(
    timezone: 'America/Guyana',
    location: 'Guyana',
    countryCode: 'gy',
    flag: 'https://flagcdn.com/w80/gy.png',
  ),
  TimeZoneItem(
    timezone: 'America/Halifax',
    location: 'Halifax',
    countryCode: 'ca',
    flag: 'https://flagcdn.com/w80/ca.png',
  ),
  TimeZoneItem(
    timezone: 'America/Havana',
    location: 'Havana',
    countryCode: 'cu',
    flag: 'https://flagcdn.com/w80/cu.png',
  ),
  TimeZoneItem(
    timezone: 'America/Hermosillo',
    location: 'Hermosillo',
    countryCode: 'mx',
    flag: 'https://flagcdn.com/w80/mx.png',
  ),
  TimeZoneItem(
    timezone: 'America/Indiana/Indianapolis',
    location: 'Indianapolis',
    countryCode: 'us',
    flag: 'https://flagcdn.com/w80/us.png',
  ),
  TimeZoneItem(
    timezone: 'America/Indiana/Knox',
    location: 'Knox',
    countryCode: 'us',
    flag: 'https://flagcdn.com/w80/us.png',
  ),
  TimeZoneItem(
    timezone: 'America/Indiana/Marengo',
    location: 'Marengo',
    countryCode: 'us',
    flag: 'https://flagcdn.com/w80/us.png',
  ),
  TimeZoneItem(
    timezone: 'America/Indiana/Petersburg',
    location: 'Petersburg',
    countryCode: 'us',
    flag: 'https://flagcdn.com/w80/us.png',
  ),
  TimeZoneItem(
    timezone: 'America/Indiana/Tell_City',
    location: 'Tell City',
    countryCode: 'us',
    flag: 'https://flagcdn.com/w80/us.png',
  ),
  TimeZoneItem(
    timezone: 'America/Indiana/Vevay',
    location: 'Vevay',
    countryCode: 'us',
    flag: 'https://flagcdn.com/w80/us.png',
  ),
  TimeZoneItem(
    timezone: 'America/Indiana/Vincennes',
    location: 'Vincennes',
    countryCode: 'us',
    flag: 'https://flagcdn.com/w80/us.png',
  ),
  TimeZoneItem(
    timezone: 'America/Indiana/Winamac',
    location: 'Winamac',
    countryCode: 'us',
    flag: 'https://flagcdn.com/w80/us.png',
  ),
  TimeZoneItem(
    timezone: 'America/Indianapolis',
    location: 'Indianapolis',
    countryCode: 'us',
    flag: 'https://flagcdn.com/w80/us.png',
  ),
  TimeZoneItem(
    timezone: 'America/Inuvik',
    location: 'Inuvik',
    countryCode: 'ca',
    flag: 'https://flagcdn.com/w80/ca.png',
  ),
  TimeZoneItem(
    timezone: 'America/Iqaluit',
    location: 'Iqaluit',
    countryCode: 'ca',
    flag: 'https://flagcdn.com/w80/ca.png',
  ),
  TimeZoneItem(
    timezone: 'America/Jamaica',
    location: 'Jamaica',
    countryCode: 'jm',
    flag: 'https://flagcdn.com/w80/jm.png',
  ),
  TimeZoneItem(
    timezone: 'America/Jujuy',
    location: 'Jujuy',
    countryCode: 'ar',
    flag: 'https://flagcdn.com/w80/ar.png',
  ),
  TimeZoneItem(
    timezone: 'America/Juneau',
    location: 'Juneau',
    countryCode: 'us',
    flag: 'https://flagcdn.com/w80/us.png',
  ),
  TimeZoneItem(
    timezone: 'America/Kentucky/Louisville',
    location: 'Louisville',
    countryCode: 'us',
    flag: 'https://flagcdn.com/w80/us.png',
  ),
  TimeZoneItem(
    timezone: 'America/Kentucky/Monticello',
    location: 'Monticello',
    countryCode: 'us',
    flag: 'https://flagcdn.com/w80/us.png',
  ),
  TimeZoneItem(
    timezone: 'America/Knox_IN',
    location: 'Knox IN',
    countryCode: 'us',
    flag: 'https://flagcdn.com/w80/us.png',
  ),
  TimeZoneItem(
    timezone: 'America/Kralendijk',
    location: 'Kralendijk',
    countryCode: 'cw',
    flag: 'https://flagcdn.com/w80/cw.png',
  ),
  TimeZoneItem(
    timezone: 'America/La_Paz',
    location: 'La Paz',
    countryCode: 'bo',
    flag: 'https://flagcdn.com/w80/bo.png',
  ),
  TimeZoneItem(
    timezone: 'America/Lima',
    location: 'Lima',
    countryCode: 'pe',
    flag: 'https://flagcdn.com/w80/pe.png',
  ),
  TimeZoneItem(
    timezone: 'America/Los_Angeles',
    location: 'Los Angeles',
    countryCode: 'us',
    flag: 'https://flagcdn.com/w80/us.png',
  ),
  TimeZoneItem(
    timezone: 'America/Louisville',
    location: 'Louisville',
    countryCode: 'us',
    flag: 'https://flagcdn.com/w80/us.png',
  ),
  TimeZoneItem(
    timezone: 'America/Lower_Princes',
    location: 'Lower Princes',
    countryCode: 'cw',
    flag: 'https://flagcdn.com/w80/cw.png',
  ),
  TimeZoneItem(
    timezone: 'America/Maceio',
    location: 'Maceio',
    countryCode: 'br',
    flag: 'https://flagcdn.com/w80/br.png',
  ),
  TimeZoneItem(
    timezone: 'America/Managua',
    location: 'Managua',
    countryCode: 'ni',
    flag: 'https://flagcdn.com/w80/ni.png',
  ),
  TimeZoneItem(
    timezone: 'America/Manaus',
    location: 'Manaus',
    countryCode: 'br',
    flag: 'https://flagcdn.com/w80/br.png',
  ),
  TimeZoneItem(
    timezone: 'America/Marigot',
    location: 'Marigot',
    countryCode: 'tt',
    flag: 'https://flagcdn.com/w80/tt.png',
  ),
  TimeZoneItem(
    timezone: 'America/Martinique',
    location: 'Martinique',
    countryCode: 'mq',
    flag: 'https://flagcdn.com/w80/mq.png',
  ),
  TimeZoneItem(
    timezone: 'America/Matamoros',
    location: 'Matamoros',
    countryCode: 'mx',
    flag: 'https://flagcdn.com/w80/mx.png',
  ),
  TimeZoneItem(
    timezone: 'America/Mazatlan',
    location: 'Mazatlan',
    countryCode: 'mx',
    flag: 'https://flagcdn.com/w80/mx.png',
  ),
  TimeZoneItem(
    timezone: 'America/Mendoza',
    location: 'Mendoza',
    countryCode: 'ar',
    flag: 'https://flagcdn.com/w80/ar.png',
  ),
  TimeZoneItem(
    timezone: 'America/Menominee',
    location: 'Menominee',
    countryCode: 'us',
    flag: 'https://flagcdn.com/w80/us.png',
  ),
  TimeZoneItem(
    timezone: 'America/Merida',
    location: 'Merida',
    countryCode: 'mx',
    flag: 'https://flagcdn.com/w80/mx.png',
  ),
  TimeZoneItem(
    timezone: 'America/Metlakatla',
    location: 'Metlakatla',
    countryCode: 'us',
    flag: 'https://flagcdn.com/w80/us.png',
  ),
  TimeZoneItem(
    timezone: 'America/Mexico_City',
    location: 'Mexico City',
    countryCode: 'mx',
    flag: 'https://flagcdn.com/w80/mx.png',
  ),
  TimeZoneItem(
    timezone: 'America/Miquelon',
    location: 'Miquelon',
    countryCode: 'pm',
    flag: 'https://flagcdn.com/w80/pm.png',
  ),
  TimeZoneItem(
    timezone: 'America/Moncton',
    location: 'Moncton',
    countryCode: 'ca',
    flag: 'https://flagcdn.com/w80/ca.png',
  ),
  TimeZoneItem(
    timezone: 'America/Monterrey',
    location: 'Monterrey',
    countryCode: 'mx',
    flag: 'https://flagcdn.com/w80/mx.png',
  ),
  TimeZoneItem(
    timezone: 'America/Montevideo',
    location: 'Montevideo',
    countryCode: 'uy',
    flag: 'https://flagcdn.com/w80/uy.png',
  ),
  TimeZoneItem(
    timezone: 'America/Montreal',
    location: 'Montreal',
    countryCode: 'ca',
    flag: 'https://flagcdn.com/w80/ca.png',
  ),
  TimeZoneItem(
    timezone: 'America/Montserrat',
    location: 'Montserrat',
    countryCode: 'ms',
    flag: 'https://flagcdn.com/w80/ms.png',
  ),
  TimeZoneItem(
    timezone: 'America/Nassau',
    location: 'Nassau',
    countryCode: 'bs',
    flag: 'https://flagcdn.com/w80/bs.png',
  ),
  TimeZoneItem(
    timezone: 'America/New_York',
    location: 'New York',
    countryCode: 'us',
    flag: 'https://flagcdn.com/w80/us.png',
  ),
  TimeZoneItem(
    timezone: 'America/Nipigon',
    location: 'Nipigon',
    countryCode: 'ca',
    flag: 'https://flagcdn.com/w80/ca.png',
  ),
  TimeZoneItem(
    timezone: 'America/Nome',
    location: 'Nome',
    countryCode: 'us',
    flag: 'https://flagcdn.com/w80/us.png',
  ),
  TimeZoneItem(
    timezone: 'America/Noronha',
    location: 'Noronha',
    countryCode: 'br',
    flag: 'https://flagcdn.com/w80/br.png',
  ),
  TimeZoneItem(
    timezone: 'America/North_Dakota/Beulah',
    location: 'Beulah',
    countryCode: 'us',
    flag: 'https://flagcdn.com/w80/us.png',
  ),
  TimeZoneItem(
    timezone: 'America/North_Dakota/Center',
    location: 'Center',
    countryCode: 'us',
    flag: 'https://flagcdn.com/w80/us.png',
  ),
  TimeZoneItem(
    timezone: 'America/North_Dakota/New_Salem',
    location: 'New Salem',
    countryCode: 'us',
    flag: 'https://flagcdn.com/w80/us.png',
  ),
  TimeZoneItem(
    timezone: 'America/Nuuk',
    location: 'Nuuk',
    countryCode: 'gl',
    flag: 'https://flagcdn.com/w80/gl.png',
  ),
  TimeZoneItem(
    timezone: 'America/Ojinaga',
    location: 'Ojinaga',
    countryCode: 'mx',
    flag: 'https://flagcdn.com/w80/mx.png',
  ),
  TimeZoneItem(
    timezone: 'America/Panama',
    location: 'Panama',
    countryCode: 'pa',
    flag: 'https://flagcdn.com/w80/pa.png',
  ),
  TimeZoneItem(
    timezone: 'America/Pangnirtung',
    location: 'Pangnirtung',
    countryCode: 'ca',
    flag: 'https://flagcdn.com/w80/ca.png',
  ),
  TimeZoneItem(
    timezone: 'America/Paramaribo',
    location: 'Paramaribo',
    countryCode: 'sr',
    flag: 'https://flagcdn.com/w80/sr.png',
  ),
  TimeZoneItem(
    timezone: 'America/Phoenix',
    location: 'Phoenix',
    countryCode: 'us',
    flag: 'https://flagcdn.com/w80/us.png',
  ),
  TimeZoneItem(
    timezone: 'America/Port_of_Spain',
    location: 'Port of Spain',
    countryCode: 'tt',
    flag: 'https://flagcdn.com/w80/tt.png',
  ),
  TimeZoneItem(
    timezone: 'America/Port-au-Prince',
    location: 'Port-au-Prince',
    countryCode: 'ht',
    flag: 'https://flagcdn.com/w80/ht.png',
  ),
  TimeZoneItem(
    timezone: 'America/Porto_Acre',
    location: 'Porto Acre',
    countryCode: 'br',
    flag: 'https://flagcdn.com/w80/br.png',
  ),
  TimeZoneItem(
    timezone: 'America/Porto_Velho',
    location: 'Porto Velho',
    countryCode: 'br',
    flag: 'https://flagcdn.com/w80/br.png',
  ),
  TimeZoneItem(
    timezone: 'America/Puerto_Rico',
    location: 'Puerto Rico',
    countryCode: 'pr',
    flag: 'https://flagcdn.com/w80/pr.png',
  ),
  TimeZoneItem(
    timezone: 'America/Punta_Arenas',
    location: 'Punta Arenas',
    countryCode: 'cl',
    flag: 'https://flagcdn.com/w80/cl.png',
  ),
  TimeZoneItem(
    timezone: 'America/Rainy_River',
    location: 'Rainy River',
    countryCode: 'ca',
    flag: 'https://flagcdn.com/w80/ca.png',
  ),
  TimeZoneItem(
    timezone: 'America/Rankin_Inlet',
    location: 'Rankin Inlet',
    countryCode: 'ca',
    flag: 'https://flagcdn.com/w80/ca.png',
  ),
  TimeZoneItem(
    timezone: 'America/Recife',
    location: 'Recife',
    countryCode: 'br',
    flag: 'https://flagcdn.com/w80/br.png',
  ),
  TimeZoneItem(
    timezone: 'America/Regina',
    location: 'Regina',
    countryCode: 'ca',
    flag: 'https://flagcdn.com/w80/ca.png',
  ),
  TimeZoneItem(
    timezone: 'America/Resolute',
    location: 'Resolute',
    countryCode: 'ca',
    flag: 'https://flagcdn.com/w80/ca.png',
  ),
  TimeZoneItem(
    timezone: 'America/Rio_Branco',
    location: 'Rio Branco',
    countryCode: 'br',
    flag: 'https://flagcdn.com/w80/br.png',
  ),
  TimeZoneItem(
    timezone: 'America/Rosario',
    location: 'Rosario',
    countryCode: 'ar',
    flag: 'https://flagcdn.com/w80/ar.png',
  ),
  TimeZoneItem(
    timezone: 'America/Santa_Isabel',
    location: 'Santa Isabel',
    countryCode: 'mx',
    flag: 'https://flagcdn.com/w80/mx.png',
  ),
  TimeZoneItem(
    timezone: 'America/Santarem',
    location: 'Santarem',
    countryCode: 'br',
    flag: 'https://flagcdn.com/w80/br.png',
  ),
  TimeZoneItem(
    timezone: 'America/Santiago',
    location: 'Santiago',
    countryCode: 'cl',
    flag: 'https://flagcdn.com/w80/cl.png',
  ),
  TimeZoneItem(
    timezone: 'America/Santo_Domingo',
    location: 'Santo Domingo',
    countryCode: 'do',
    flag: 'https://flagcdn.com/w80/do.png',
  ),
  TimeZoneItem(
    timezone: 'America/Sao_Paulo',
    location: 'Sao Paulo',
    countryCode: 'br',
    flag: 'https://flagcdn.com/w80/br.png',
  ),
  TimeZoneItem(
    timezone: 'America/Scoresbysund',
    location: 'Scoresbysund',
    countryCode: 'gl',
    flag: 'https://flagcdn.com/w80/gl.png',
  ),
  TimeZoneItem(
    timezone: 'America/Shiprock',
    location: 'Shiprock',
    countryCode: 'us',
    flag: 'https://flagcdn.com/w80/us.png',
  ),
  TimeZoneItem(
    timezone: 'America/Sitka',
    location: 'Sitka',
    countryCode: 'us',
    flag: 'https://flagcdn.com/w80/us.png',
  ),
  TimeZoneItem(
    timezone: 'America/St_Barthelemy',
    location: 'St Barthelemy',
    countryCode: 'tt',
    flag: 'https://flagcdn.com/w80/tt.png',
  ),
  TimeZoneItem(
    timezone: 'America/St_Johns',
    location: 'St Johns',
    countryCode: 'ca',
    flag: 'https://flagcdn.com/w80/ca.png',
  ),
  TimeZoneItem(
    timezone: 'America/St_Kitts',
    location: 'St Kitts',
    countryCode: 'kn',
    flag: 'https://flagcdn.com/w80/kn.png',
  ),
  TimeZoneItem(
    timezone: 'America/St_Lucia',
    location: 'St Lucia',
    countryCode: 'lc',
    flag: 'https://flagcdn.com/w80/lc.png',
  ),
  TimeZoneItem(
    timezone: 'America/St_Thomas',
    location: 'St Thomas',
    countryCode: 'vi',
    flag: 'https://flagcdn.com/w80/vi.png',
  ),
  TimeZoneItem(
    timezone: 'America/St_Vincent',
    location: 'St Vincent',
    countryCode: 'vc',
    flag: 'https://flagcdn.com/w80/vc.png',
  ),
  TimeZoneItem(
    timezone: 'America/Swift_Current',
    location: 'Swift Current',
    countryCode: 'ca',
    flag: 'https://flagcdn.com/w80/ca.png',
  ),
  TimeZoneItem(
    timezone: 'America/Tegucigalpa',
    location: 'Tegucigalpa',
    countryCode: 'hn',
    flag: 'https://flagcdn.com/w80/hn.png',
  ),
  TimeZoneItem(
    timezone: 'America/Thule',
    location: 'Thule',
    countryCode: 'gl',
    flag: 'https://flagcdn.com/w80/gl.png',
  ),
  TimeZoneItem(
    timezone: 'America/Thunder_Bay',
    location: 'Thunder Bay',
    countryCode: 'ca',
    flag: 'https://flagcdn.com/w80/ca.png',
  ),
  TimeZoneItem(
    timezone: 'America/Tijuana',
    location: 'Tijuana',
    countryCode: 'mx',
    flag: 'https://flagcdn.com/w80/mx.png',
  ),
  TimeZoneItem(
    timezone: 'America/Toronto',
    location: 'Toronto',
    countryCode: 'ca',
    flag: 'https://flagcdn.com/w80/ca.png',
  ),
  TimeZoneItem(
    timezone: 'America/Tortola',
    location: 'Tortola',
    countryCode: 'vg',
    flag: 'https://flagcdn.com/w80/vg.png',
  ),
  TimeZoneItem(
    timezone: 'America/Vancouver',
    location: 'Vancouver',
    countryCode: 'ca',
    flag: 'https://flagcdn.com/w80/ca.png',
  ),
  TimeZoneItem(
    timezone: 'America/Virgin',
    location: 'Virgin',
    countryCode: 'vi',
    flag: 'https://flagcdn.com/w80/vi.png',
  ),
  TimeZoneItem(
    timezone: 'America/Whitehorse',
    location: 'Whitehorse',
    countryCode: 'ca',
    flag: 'https://flagcdn.com/w80/ca.png',
  ),
  TimeZoneItem(
    timezone: 'America/Winnipeg',
    location: 'Winnipeg',
    countryCode: 'ca',
    flag: 'https://flagcdn.com/w80/ca.png',
  ),
  TimeZoneItem(
    timezone: 'America/Yakutat',
    location: 'Yakutat',
    countryCode: 'us',
    flag: 'https://flagcdn.com/w80/us.png',
  ),
  TimeZoneItem(
    timezone: 'America/Yellowknife',
    location: 'Yellowknife',
    countryCode: 'ca',
    flag: 'https://flagcdn.com/w80/ca.png',
  ),
  TimeZoneItem(
    timezone: 'Antarctica/Casey',
    location: 'Casey',
    countryCode: 'aq',
    flag: 'https://flagcdn.com/w80/aq.png',
  ),
  TimeZoneItem(
    timezone: 'Antarctica/Davis',
    location: 'Davis',
    countryCode: 'aq',
    flag: 'https://flagcdn.com/w80/aq.png',
  ),
  TimeZoneItem(
    timezone: 'Antarctica/DumontDUrville',
    location: 'DumontDUrville',
    countryCode: 'aq',
    flag: 'https://flagcdn.com/w80/aq.png',
  ),
  TimeZoneItem(
    timezone: 'Antarctica/Macquarie',
    location: 'Macquarie',
    countryCode: 'au',
    flag: 'https://flagcdn.com/w80/au.png',
  ),
  TimeZoneItem(
    timezone: 'Antarctica/Mawson',
    location: 'Mawson',
    countryCode: 'aq',
    flag: 'https://flagcdn.com/w80/aq.png',
  ),
  TimeZoneItem(
    timezone: 'Antarctica/McMurdo',
    location: 'McMurdo',
    countryCode: 'aq',
    flag: 'https://flagcdn.com/w80/aq.png',
  ),
  TimeZoneItem(
    timezone: 'Antarctica/Palmer',
    location: 'Palmer',
    countryCode: 'aq',
    flag: 'https://flagcdn.com/w80/aq.png',
  ),
  TimeZoneItem(
    timezone: 'Antarctica/Rothera',
    location: 'Rothera',
    countryCode: 'aq',
    flag: 'https://flagcdn.com/w80/aq.png',
  ),
  TimeZoneItem(
    timezone: 'Antarctica/South_Pole',
    location: 'South Pole',
    countryCode: 'aq',
    flag: 'https://flagcdn.com/w80/aq.png',
  ),
  TimeZoneItem(
    timezone: 'Antarctica/Syowa',
    location: 'Syowa',
    countryCode: 'aq',
    flag: 'https://flagcdn.com/w80/aq.png',
  ),
  TimeZoneItem(
    timezone: 'Antarctica/Troll',
    location: 'Troll',
    countryCode: 'aq',
    flag: 'https://flagcdn.com/w80/aq.png',
  ),
  TimeZoneItem(
    timezone: 'Antarctica/Vostok',
    location: 'Vostok',
    countryCode: 'aq',
    flag: 'https://flagcdn.com/w80/aq.png',
  ),
  TimeZoneItem(
    timezone: 'Arctic/Longyearbyen',
    location: 'Longyearbyen',
    countryCode: 'no',
    flag: 'https://flagcdn.com/w80/no.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Aden',
    location: 'Aden',
    countryCode: 'ye',
    flag: 'https://flagcdn.com/w80/ye.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Almaty',
    location: 'Almaty',
    countryCode: 'kz',
    flag: 'https://flagcdn.com/w80/kz.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Amman',
    location: 'Amman',
    countryCode: 'jo',
    flag: 'https://flagcdn.com/w80/jo.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Anadyr',
    location: 'Anadyr',
    countryCode: 'ru',
    flag: 'https://flagcdn.com/w80/ru.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Aqtau',
    location: 'Aqtau',
    countryCode: 'kz',
    flag: 'https://flagcdn.com/w80/kz.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Aqtobe',
    location: 'Aqtobe',
    countryCode: 'kz',
    flag: 'https://flagcdn.com/w80/kz.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Ashgabat',
    location: 'Ashgabat',
    countryCode: 'tm',
    flag: 'https://flagcdn.com/w80/tm.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Ashkhabad',
    location: 'Ashkhabad',
    countryCode: 'tm',
    flag: 'https://flagcdn.com/w80/tm.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Atyrau',
    location: 'Atyrau',
    countryCode: 'kz',
    flag: 'https://flagcdn.com/w80/kz.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Baghdad',
    location: 'Baghdad',
    countryCode: 'iq',
    flag: 'https://flagcdn.com/w80/iq.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Bahrain',
    location: 'Bahrain',
    countryCode: 'bh',
    flag: 'https://flagcdn.com/w80/bh.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Baku',
    location: 'Baku',
    countryCode: 'az',
    flag: 'https://flagcdn.com/w80/az.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Bangkok',
    location: 'Bangkok',
    countryCode: 'th',
    flag: 'https://flagcdn.com/w80/th.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Barnaul',
    location: 'Barnaul',
    countryCode: 'ru',
    flag: 'https://flagcdn.com/w80/ru.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Beirut',
    location: 'Beirut',
    countryCode: 'lb',
    flag: 'https://flagcdn.com/w80/lb.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Bishkek',
    location: 'Bishkek',
    countryCode: 'kg',
    flag: 'https://flagcdn.com/w80/kg.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Brunei',
    location: 'Brunei',
    countryCode: 'bn',
    flag: 'https://flagcdn.com/w80/bn.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Calcutta',
    location: 'Calcutta',
    countryCode: 'in',
    flag: 'https://flagcdn.com/w80/in.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Chita',
    location: 'Chita',
    countryCode: 'ru',
    flag: 'https://flagcdn.com/w80/ru.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Choibalsan',
    location: 'Choibalsan',
    countryCode: 'mn',
    flag: 'https://flagcdn.com/w80/mn.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Chongqing',
    location: 'Chongqing',
    countryCode: 'cn',
    flag: 'https://flagcdn.com/w80/cn.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Chungking',
    location: 'Chungking',
    countryCode: 'cn',
    flag: 'https://flagcdn.com/w80/cn.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Colombo',
    location: 'Colombo',
    countryCode: 'lk',
    flag: 'https://flagcdn.com/w80/lk.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Dacca',
    location: 'Dacca',
    countryCode: 'bd',
    flag: 'https://flagcdn.com/w80/bd.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Damascus',
    location: 'Damascus',
    countryCode: 'sy',
    flag: 'https://flagcdn.com/w80/sy.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Dhaka',
    location: 'Dhaka',
    countryCode: 'bd',
    flag: 'https://flagcdn.com/w80/bd.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Dili',
    location: 'Dili',
    countryCode: 'tl',
    flag: 'https://flagcdn.com/w80/tl.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Dubai',
    location: 'Dubai',
    countryCode: 'ae',
    flag: 'https://flagcdn.com/w80/ae.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Dushanbe',
    location: 'Dushanbe',
    countryCode: 'tj',
    flag: 'https://flagcdn.com/w80/tj.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Famagusta',
    location: 'Famagusta',
    countryCode: 'cy',
    flag: 'https://flagcdn.com/w80/cy.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Gaza',
    location: 'Gaza',
    countryCode: 'ps',
    flag: 'https://flagcdn.com/w80/ps.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Harbin',
    location: 'Harbin',
    countryCode: 'cn',
    flag: 'https://flagcdn.com/w80/cn.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Hebron',
    location: 'Hebron',
    countryCode: 'ps',
    flag: 'https://flagcdn.com/w80/ps.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Ho_Chi_Minh',
    location: 'Ho Chi Minh',
    countryCode: 'vn',
    flag: 'https://flagcdn.com/w80/vn.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Hong_Kong',
    location: 'Hong Kong',
    countryCode: 'hk',
    flag: 'https://flagcdn.com/w80/hk.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Hovd',
    location: 'Hovd',
    countryCode: 'mn',
    flag: 'https://flagcdn.com/w80/mn.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Irkutsk',
    location: 'Irkutsk',
    countryCode: 'ru',
    flag: 'https://flagcdn.com/w80/ru.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Istanbul',
    location: 'Istanbul',
    countryCode: 'tr',
    flag: 'https://flagcdn.com/w80/tr.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Jakarta',
    location: 'Jakarta',
    countryCode: 'id',
    flag: 'https://flagcdn.com/w80/id.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Jayapura',
    location: 'Jayapura',
    countryCode: 'id',
    flag: 'https://flagcdn.com/w80/id.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Jerusalem',
    location: 'Jerusalem',
    countryCode: 'il',
    flag: 'https://flagcdn.com/w80/il.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Kabul',
    location: 'Kabul',
    countryCode: 'af',
    flag: 'https://flagcdn.com/w80/af.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Kamchatka',
    location: 'Kamchatka',
    countryCode: 'ru',
    flag: 'https://flagcdn.com/w80/ru.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Karachi',
    location: 'Karachi',
    countryCode: 'pk',
    flag: 'https://flagcdn.com/w80/pk.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Kashgar',
    location: 'Kashgar',
    countryCode: 'cn',
    flag: 'https://flagcdn.com/w80/cn.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Kathmandu',
    location: 'Kathmandu',
    countryCode: 'np',
    flag: 'https://flagcdn.com/w80/np.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Katmandu',
    location: 'Katmandu',
    countryCode: 'np',
    flag: 'https://flagcdn.com/w80/np.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Khandyga',
    location: 'Khandyga',
    countryCode: 'ru',
    flag: 'https://flagcdn.com/w80/ru.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Kolkata',
    location: 'Kolkata',
    countryCode: 'in',
    flag: 'https://flagcdn.com/w80/in.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Krasnoyarsk',
    location: 'Krasnoyarsk',
    countryCode: 'ru',
    flag: 'https://flagcdn.com/w80/ru.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Kuala_Lumpur',
    location: 'Kuala Lumpur',
    countryCode: 'my',
    flag: 'https://flagcdn.com/w80/my.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Kuching',
    location: 'Kuching',
    countryCode: 'my',
    flag: 'https://flagcdn.com/w80/my.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Kuwait',
    location: 'Kuwait',
    countryCode: 'kw',
    flag: 'https://flagcdn.com/w80/kw.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Macao',
    location: 'Macao',
    countryCode: 'mo',
    flag: 'https://flagcdn.com/w80/mo.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Macau',
    location: 'Macau',
    countryCode: 'mo',
    flag: 'https://flagcdn.com/w80/mo.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Magadan',
    location: 'Magadan',
    countryCode: 'ru',
    flag: 'https://flagcdn.com/w80/ru.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Makassar',
    location: 'Makassar',
    countryCode: 'id',
    flag: 'https://flagcdn.com/w80/id.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Manila',
    location: 'Manila',
    countryCode: 'ph',
    flag: 'https://flagcdn.com/w80/ph.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Muscat',
    location: 'Muscat',
    countryCode: 'om',
    flag: 'https://flagcdn.com/w80/om.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Nicosia',
    location: 'Nicosia',
    countryCode: 'cy',
    flag: 'https://flagcdn.com/w80/cy.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Novokuznetsk',
    location: 'Novokuznetsk',
    countryCode: 'ru',
    flag: 'https://flagcdn.com/w80/ru.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Novosibirsk',
    location: 'Novosibirsk',
    countryCode: 'ru',
    flag: 'https://flagcdn.com/w80/ru.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Omsk',
    location: 'Omsk',
    countryCode: 'ru',
    flag: 'https://flagcdn.com/w80/ru.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Oral',
    location: 'Oral',
    countryCode: 'kz',
    flag: 'https://flagcdn.com/w80/kz.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Phnom_Penh',
    location: 'Phnom Penh',
    countryCode: 'kh',
    flag: 'https://flagcdn.com/w80/kh.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Pontianak',
    location: 'Pontianak',
    countryCode: 'id',
    flag: 'https://flagcdn.com/w80/id.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Pyongyang',
    location: 'Pyongyang',
    countryCode: 'kp',
    flag: 'https://flagcdn.com/w80/kp.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Qatar',
    location: 'Qatar',
    countryCode: 'qa',
    flag: 'https://flagcdn.com/w80/qa.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Qostanay',
    location: 'Qostanay',
    countryCode: 'kz',
    flag: 'https://flagcdn.com/w80/kz.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Qyzylorda',
    location: 'Qyzylorda',
    countryCode: 'kz',
    flag: 'https://flagcdn.com/w80/kz.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Rangoon',
    location: 'Rangoon',
    countryCode: 'mm',
    flag: 'https://flagcdn.com/w80/mm.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Riyadh',
    location: 'Riyadh',
    countryCode: 'sa',
    flag: 'https://flagcdn.com/w80/sa.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Saigon',
    location: 'Saigon',
    countryCode: 'vn',
    flag: 'https://flagcdn.com/w80/vn.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Sakhalin',
    location: 'Sakhalin',
    countryCode: 'ru',
    flag: 'https://flagcdn.com/w80/ru.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Samarkand',
    location: 'Samarkand',
    countryCode: 'uz',
    flag: 'https://flagcdn.com/w80/uz.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Seoul',
    location: 'Seoul',
    countryCode: 'kr',
    flag: 'https://flagcdn.com/w80/kr.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Shanghai',
    location: 'Shanghai',
    countryCode: 'cn',
    flag: 'https://flagcdn.com/w80/cn.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Singapore',
    location: 'Singapore',
    countryCode: 'sg',
    flag: 'https://flagcdn.com/w80/sg.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Srednekolymsk',
    location: 'Srednekolymsk',
    countryCode: 'ru',
    flag: 'https://flagcdn.com/w80/ru.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Taipei',
    location: 'Taipei',
    countryCode: 'tw',
    flag: 'https://flagcdn.com/w80/tw.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Tashkent',
    location: 'Tashkent',
    countryCode: 'uz',
    flag: 'https://flagcdn.com/w80/uz.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Tbilisi',
    location: 'Tbilisi',
    countryCode: 'ge',
    flag: 'https://flagcdn.com/w80/ge.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Tehran',
    location: 'Tehran',
    countryCode: 'ir',
    flag: 'https://flagcdn.com/w80/ir.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Tel_Aviv',
    location: 'Tel Aviv',
    countryCode: 'il',
    flag: 'https://flagcdn.com/w80/il.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Thimbu',
    location: 'Thimbu',
    countryCode: 'bt',
    flag: 'https://flagcdn.com/w80/bt.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Thimphu',
    location: 'Thimphu',
    countryCode: 'bt',
    flag: 'https://flagcdn.com/w80/bt.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Tokyo',
    location: 'Tokyo',
    countryCode: 'jp',
    flag: 'https://flagcdn.com/w80/jp.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Tomsk',
    location: 'Tomsk',
    countryCode: 'ru',
    flag: 'https://flagcdn.com/w80/ru.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Ujung_Pandang',
    location: 'Ujung Pandang',
    countryCode: 'id',
    flag: 'https://flagcdn.com/w80/id.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Ulaanbaatar',
    location: 'Ulaanbaatar',
    countryCode: 'mn',
    flag: 'https://flagcdn.com/w80/mn.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Ulan_Bator',
    location: 'Ulan Bator',
    countryCode: 'mn',
    flag: 'https://flagcdn.com/w80/mn.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Urumqi',
    location: 'Urumqi',
    countryCode: 'cn',
    flag: 'https://flagcdn.com/w80/cn.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Ust-Nera',
    location: 'Ust-Nera',
    countryCode: 'ru',
    flag: 'https://flagcdn.com/w80/ru.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Vientiane',
    location: 'Vientiane',
    countryCode: 'la',
    flag: 'https://flagcdn.com/w80/la.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Vladivostok',
    location: 'Vladivostok',
    countryCode: 'ru',
    flag: 'https://flagcdn.com/w80/ru.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Yakutsk',
    location: 'Yakutsk',
    countryCode: 'ru',
    flag: 'https://flagcdn.com/w80/ru.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Yangon',
    location: 'Yangon',
    countryCode: 'mm',
    flag: 'https://flagcdn.com/w80/mm.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Yekaterinburg',
    location: 'Yekaterinburg',
    countryCode: 'ru',
    flag: 'https://flagcdn.com/w80/ru.png',
  ),
  TimeZoneItem(
    timezone: 'Asia/Yerevan',
    location: 'Yerevan',
    countryCode: 'am',
    flag: 'https://flagcdn.com/w80/am.png',
  ),
  TimeZoneItem(
    timezone: 'Atlantic/Azores',
    location: 'Azores',
    countryCode: 'pt',
    flag: 'https://flagcdn.com/w80/pt.png',
  ),
  TimeZoneItem(
    timezone: 'Atlantic/Bermuda',
    location: 'Bermuda',
    countryCode: 'bm',
    flag: 'https://flagcdn.com/w80/bm.png',
  ),
  TimeZoneItem(
    timezone: 'Atlantic/Canary',
    location: 'Canary',
    countryCode: 'es',
    flag: 'https://flagcdn.com/w80/es.png',
  ),
  TimeZoneItem(
    timezone: 'Atlantic/Cape_Verde',
    location: 'Cape Verde',
    countryCode: 'cv',
    flag: 'https://flagcdn.com/w80/cv.png',
  ),
  TimeZoneItem(
    timezone: 'Atlantic/Faeroe',
    location: 'Faeroe',
    countryCode: 'fo',
    flag: 'https://flagcdn.com/w80/fo.png',
  ),
  TimeZoneItem(
    timezone: 'Atlantic/Faroe',
    location: 'Faroe',
    countryCode: 'fo',
    flag: 'https://flagcdn.com/w80/fo.png',
  ),
  TimeZoneItem(
    timezone: 'Atlantic/Jan_Mayen',
    location: 'Jan Mayen',
    countryCode: 'no',
    flag: 'https://flagcdn.com/w80/no.png',
  ),
  TimeZoneItem(
    timezone: 'Atlantic/Madeira',
    location: 'Madeira',
    countryCode: 'pt',
    flag: 'https://flagcdn.com/w80/pt.png',
  ),
  TimeZoneItem(
    timezone: 'Atlantic/Reykjavik',
    location: 'Reykjavik',
    countryCode: 'is',
    flag: 'https://flagcdn.com/w80/is.png',
  ),
  TimeZoneItem(
    timezone: 'Atlantic/South_Georgia',
    location: 'South Georgia',
    countryCode: 'gs',
    flag: 'https://flagcdn.com/w80/gs.png',
  ),
  TimeZoneItem(
    timezone: 'Atlantic/St_Helena',
    location: 'St Helena',
    countryCode: 'sh',
    flag: 'https://flagcdn.com/w80/sh.png',
  ),
  TimeZoneItem(
    timezone: 'Atlantic/Stanley',
    location: 'Stanley',
    countryCode: 'fk',
    flag: 'https://flagcdn.com/w80/fk.png',
  ),
  TimeZoneItem(
    timezone: 'Australia/ACT',
    location: 'ACT',
    countryCode: 'au',
    flag: 'https://flagcdn.com/w80/au.png',
  ),
  TimeZoneItem(
    timezone: 'Australia/Adelaide',
    location: 'Adelaide',
    countryCode: 'au',
    flag: 'https://flagcdn.com/w80/au.png',
  ),
  TimeZoneItem(
    timezone: 'Australia/Brisbane',
    location: 'Brisbane',
    countryCode: 'au',
    flag: 'https://flagcdn.com/w80/au.png',
  ),
  TimeZoneItem(
    timezone: 'Australia/Broken_Hill',
    location: 'Broken Hill',
    countryCode: 'au',
    flag: 'https://flagcdn.com/w80/au.png',
  ),
  TimeZoneItem(
    timezone: 'Australia/Canberra',
    location: 'Canberra',
    countryCode: 'au',
    flag: 'https://flagcdn.com/w80/au.png',
  ),
  TimeZoneItem(
    timezone: 'Australia/Currie',
    location: 'Currie',
    countryCode: 'au',
    flag: 'https://flagcdn.com/w80/au.png',
  ),
  TimeZoneItem(
    timezone: 'Australia/Darwin',
    location: 'Darwin',
    countryCode: 'au',
    flag: 'https://flagcdn.com/w80/au.png',
  ),
  TimeZoneItem(
    timezone: 'Australia/Eucla',
    location: 'Eucla',
    countryCode: 'au',
    flag: 'https://flagcdn.com/w80/au.png',
  ),
  TimeZoneItem(
    timezone: 'Australia/Hobart',
    location: 'Hobart',
    countryCode: 'au',
    flag: 'https://flagcdn.com/w80/au.png',
  ),
  TimeZoneItem(
    timezone: 'Australia/LHI',
    location: 'LHI',
    countryCode: 'au',
    flag: 'https://flagcdn.com/w80/au.png',
  ),
  TimeZoneItem(
    timezone: 'Australia/Lindeman',
    location: 'Lindeman',
    countryCode: 'au',
    flag: 'https://flagcdn.com/w80/au.png',
  ),
  TimeZoneItem(
    timezone: 'Australia/Lord_Howe',
    location: 'Lord Howe',
    countryCode: 'au',
    flag: 'https://flagcdn.com/w80/au.png',
  ),
  TimeZoneItem(
    timezone: 'Australia/Melbourne',
    location: 'Melbourne',
    countryCode: 'au',
    flag: 'https://flagcdn.com/w80/au.png',
  ),
  TimeZoneItem(
    timezone: 'Australia/North',
    location: 'North',
    countryCode: 'au',
    flag: 'https://flagcdn.com/w80/au.png',
  ),
  TimeZoneItem(
    timezone: 'Australia/NSW',
    location: 'NSW',
    countryCode: 'au',
    flag: 'https://flagcdn.com/w80/au.png',
  ),
  TimeZoneItem(
    timezone: 'Australia/Perth',
    location: 'Perth',
    countryCode: 'au',
    flag: 'https://flagcdn.com/w80/au.png',
  ),
  TimeZoneItem(
    timezone: 'Australia/Queensland',
    location: 'Queensland',
    countryCode: 'au',
    flag: 'https://flagcdn.com/w80/au.png',
  ),
  TimeZoneItem(
    timezone: 'Australia/South',
    location: 'South',
    countryCode: 'au',
    flag: 'https://flagcdn.com/w80/au.png',
  ),
  TimeZoneItem(
    timezone: 'Australia/Sydney',
    location: 'Sydney',
    countryCode: 'au',
    flag: 'https://flagcdn.com/w80/au.png',
  ),
  TimeZoneItem(
    timezone: 'Australia/Tasmania',
    location: 'Tasmania',
    countryCode: 'au',
    flag: 'https://flagcdn.com/w80/au.png',
  ),
  TimeZoneItem(
    timezone: 'Australia/Victoria',
    location: 'Victoria',
    countryCode: 'au',
    flag: 'https://flagcdn.com/w80/au.png',
  ),
  TimeZoneItem(
    timezone: 'Australia/West',
    location: 'West',
    countryCode: 'au',
    flag: 'https://flagcdn.com/w80/au.png',
  ),
  TimeZoneItem(
    timezone: 'Australia/Yancowinna',
    location: 'Yancowinna',
    countryCode: 'au',
    flag: 'https://flagcdn.com/w80/au.png',
  ),
  TimeZoneItem(
    timezone: 'Brazil/Acre',
    location: 'Acre',
    countryCode: 'br',
    flag: 'https://flagcdn.com/w80/br.png',
  ),
  TimeZoneItem(
    timezone: 'Brazil/DeNoronha',
    location: 'DeNoronha',
    countryCode: 'br',
    flag: 'https://flagcdn.com/w80/br.png',
  ),
  TimeZoneItem(
    timezone: 'Brazil/East',
    location: 'East',
    countryCode: 'br',
    flag: 'https://flagcdn.com/w80/br.png',
  ),
  TimeZoneItem(
    timezone: 'Brazil/West',
    location: 'West',
    countryCode: 'br',
    flag: 'https://flagcdn.com/w80/br.png',
  ),
  TimeZoneItem(
    timezone: 'Canada/Atlantic',
    location: 'Atlantic',
    countryCode: 'ca',
    flag: 'https://flagcdn.com/w80/ca.png',
  ),
  TimeZoneItem(
    timezone: 'Canada/Central',
    location: 'Central',
    countryCode: 'ca',
    flag: 'https://flagcdn.com/w80/ca.png',
  ),
  TimeZoneItem(
    timezone: 'Canada/Eastern',
    location: 'Eastern',
    countryCode: 'ca',
    flag: 'https://flagcdn.com/w80/ca.png',
  ),
  TimeZoneItem(
    timezone: 'Canada/Mountain',
    location: 'Mountain',
    countryCode: 'ca',
    flag: 'https://flagcdn.com/w80/ca.png',
  ),
  TimeZoneItem(
    timezone: 'Canada/Newfoundland',
    location: 'Newfoundland',
    countryCode: 'ca',
    flag: 'https://flagcdn.com/w80/ca.png',
  ),
  TimeZoneItem(
    timezone: 'Canada/Pacific',
    location: 'Pacific',
    countryCode: 'ca',
    flag: 'https://flagcdn.com/w80/ca.png',
  ),
  TimeZoneItem(
    timezone: 'Canada/Saskatchewan',
    location: 'Saskatchewan',
    countryCode: 'ca',
    flag: 'https://flagcdn.com/w80/ca.png',
  ),
  TimeZoneItem(
    timezone: 'Canada/Yukon',
    location: 'Yukon',
    countryCode: 'ca',
    flag: 'https://flagcdn.com/w80/ca.png',
  ),
  TimeZoneItem(
    timezone: 'CET',
    location: 'CET',
    countryCode: 'be',
    flag: 'https://flagcdn.com/w80/be.png',
  ),
  TimeZoneItem(
    timezone: 'Chile/Continental',
    location: 'Continental',
    countryCode: 'cl',
    flag: 'https://flagcdn.com/w80/cl.png',
  ),
  TimeZoneItem(
    timezone: 'Chile/EasterIsland',
    location: 'EasterIsland',
    countryCode: 'cl',
    flag: 'https://flagcdn.com/w80/cl.png',
  ),
  TimeZoneItem(
    timezone: 'CST6CDT',
    location: 'CST6CDT',
    countryCode: 'us',
    flag: 'https://flagcdn.com/w80/us.png',
  ),
  TimeZoneItem(
    timezone: 'Cuba',
    location: 'Cuba',
    countryCode: 'cu',
    flag: 'https://flagcdn.com/w80/cu.png',
  ),
  TimeZoneItem(
    timezone: 'EET',
    location: 'EET',
    countryCode: 'gr',
    flag: 'https://flagcdn.com/w80/gr.png',
  ),
  TimeZoneItem(
    timezone: 'Egypt',
    location: 'Egypt',
    countryCode: 'eg',
    flag: 'https://flagcdn.com/w80/eg.png',
  ),
  TimeZoneItem(
    timezone: 'Eire',
    location: 'Eire',
    countryCode: 'ie',
    flag: 'https://flagcdn.com/w80/ie.png',
  ),
  TimeZoneItem(
    timezone: 'EST',
    location: 'EST',
    countryCode: 'pa',
    flag: 'https://flagcdn.com/w80/pa.png',
  ),
  TimeZoneItem(
    timezone: 'EST5EDT',
    location: 'EST5EDT',
    countryCode: 'us',
    flag: 'https://flagcdn.com/w80/us.png',
  ),
  TimeZoneItem(
    timezone: 'Etc/GMT',
    location: 'GMT',
    countryCode: '',
    flag: '',
  ),
  TimeZoneItem(
    timezone: 'Etc/GMT-0',
    location: 'GMT-0',
    countryCode: '',
    flag: '',
  ),
  TimeZoneItem(
    timezone: 'Etc/GMT-1',
    location: 'GMT-1',
    countryCode: '',
    flag: '',
  ),
  TimeZoneItem(
    timezone: 'Etc/GMT-10',
    location: 'GMT-10',
    countryCode: '',
    flag: '',
  ),
  TimeZoneItem(
    timezone: 'Etc/GMT-11',
    location: 'GMT-11',
    countryCode: '',
    flag: '',
  ),
  TimeZoneItem(
    timezone: 'Etc/GMT-12',
    location: 'GMT-12',
    countryCode: '',
    flag: '',
  ),
  TimeZoneItem(
    timezone: 'Etc/GMT-13',
    location: 'GMT-13',
    countryCode: '',
    flag: '',
  ),
  TimeZoneItem(
    timezone: 'Etc/GMT-14',
    location: 'GMT-14',
    countryCode: '',
    flag: '',
  ),
  TimeZoneItem(
    timezone: 'Etc/GMT-2',
    location: 'GMT-2',
    countryCode: '',
    flag: '',
  ),
  TimeZoneItem(
    timezone: 'Etc/GMT-3',
    location: 'GMT-3',
    countryCode: '',
    flag: '',
  ),
  TimeZoneItem(
    timezone: 'Etc/GMT-4',
    location: 'GMT-4',
    countryCode: '',
    flag: '',
  ),
  TimeZoneItem(
    timezone: 'Etc/GMT-5',
    location: 'GMT-5',
    countryCode: '',
    flag: '',
  ),
  TimeZoneItem(
    timezone: 'Etc/GMT-6',
    location: 'GMT-6',
    countryCode: '',
    flag: '',
  ),
  TimeZoneItem(
    timezone: 'Etc/GMT-7',
    location: 'GMT-7',
    countryCode: '',
    flag: '',
  ),
  TimeZoneItem(
    timezone: 'Etc/GMT-8',
    location: 'GMT-8',
    countryCode: '',
    flag: '',
  ),
  TimeZoneItem(
    timezone: 'Etc/GMT-9',
    location: 'GMT-9',
    countryCode: '',
    flag: '',
  ),
  TimeZoneItem(
    timezone: 'Etc/GMT+0',
    location: 'GMT+0',
    countryCode: '',
    flag: '',
  ),
  TimeZoneItem(
    timezone: 'Etc/GMT+1',
    location: 'GMT+1',
    countryCode: '',
    flag: '',
  ),
  TimeZoneItem(
    timezone: 'Etc/GMT+10',
    location: 'GMT+10',
    countryCode: '',
    flag: '',
  ),
  TimeZoneItem(
    timezone: 'Etc/GMT+11',
    location: 'GMT+11',
    countryCode: '',
    flag: '',
  ),
  TimeZoneItem(
    timezone: 'Etc/GMT+12',
    location: 'GMT+12',
    countryCode: '',
    flag: '',
  ),
  TimeZoneItem(
    timezone: 'Etc/GMT+2',
    location: 'GMT+2',
    countryCode: '',
    flag: '',
  ),
  TimeZoneItem(
    timezone: 'Etc/GMT+3',
    location: 'GMT+3',
    countryCode: '',
    flag: '',
  ),
  TimeZoneItem(
    timezone: 'Etc/GMT+4',
    location: 'GMT+4',
    countryCode: '',
    flag: '',
  ),
  TimeZoneItem(
    timezone: 'Etc/GMT+5',
    location: 'GMT+5',
    countryCode: '',
    flag: '',
  ),
  TimeZoneItem(
    timezone: 'Etc/GMT+6',
    location: 'GMT+6',
    countryCode: '',
    flag: '',
  ),
  TimeZoneItem(
    timezone: 'Etc/GMT+7',
    location: 'GMT+7',
    countryCode: '',
    flag: '',
  ),
  TimeZoneItem(
    timezone: 'Etc/GMT+8',
    location: 'GMT+8',
    countryCode: '',
    flag: '',
  ),
  TimeZoneItem(
    timezone: 'Etc/GMT+9',
    location: 'GMT+9',
    countryCode: '',
    flag: '',
  ),
  TimeZoneItem(
    timezone: 'Etc/GMT0',
    location: 'GMT0',
    countryCode: '',
    flag: '',
  ),
  TimeZoneItem(
    timezone: 'Etc/Greenwich',
    location: 'Greenwich',
    countryCode: '',
    flag: '',
  ),
  TimeZoneItem(
    timezone: 'Etc/UCT',
    location: 'UCT',
    countryCode: '',
    flag: '',
  ),
  TimeZoneItem(
    timezone: 'Etc/Universal',
    location: 'Universal',
    countryCode: '',
    flag: '',
  ),
  TimeZoneItem(
    timezone: 'Etc/UTC',
    location: 'UTC',
    countryCode: '',
    flag: '',
  ),
  TimeZoneItem(
    timezone: 'Etc/Zulu',
    location: 'Zulu',
    countryCode: '',
    flag: '',
  ),
  TimeZoneItem(
    timezone: 'Europe/Amsterdam',
    location: 'Amsterdam',
    countryCode: 'nl',
    flag: 'https://flagcdn.com/w80/nl.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Andorra',
    location: 'Andorra',
    countryCode: 'ad',
    flag: 'https://flagcdn.com/w80/ad.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Astrakhan',
    location: 'Astrakhan',
    countryCode: 'ru',
    flag: 'https://flagcdn.com/w80/ru.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Athens',
    location: 'Athens',
    countryCode: 'gr',
    flag: 'https://flagcdn.com/w80/gr.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Belfast',
    location: 'Belfast',
    countryCode: 'gb',
    flag: 'https://flagcdn.com/w80/gb.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Belgrade',
    location: 'Belgrade',
    countryCode: 'rs',
    flag: 'https://flagcdn.com/w80/rs.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Berlin',
    location: 'Berlin',
    countryCode: 'de',
    flag: 'https://flagcdn.com/w80/de.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Bratislava',
    location: 'Bratislava',
    countryCode: 'cz',
    flag: 'https://flagcdn.com/w80/cz.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Brussels',
    location: 'Brussels',
    countryCode: 'be',
    flag: 'https://flagcdn.com/w80/be.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Bucharest',
    location: 'Bucharest',
    countryCode: 'ro',
    flag: 'https://flagcdn.com/w80/ro.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Budapest',
    location: 'Budapest',
    countryCode: 'hu',
    flag: 'https://flagcdn.com/w80/hu.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Busingen',
    location: 'Busingen',
    countryCode: 'ch',
    flag: 'https://flagcdn.com/w80/ch.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Chisinau',
    location: 'Chisinau',
    countryCode: 'md',
    flag: 'https://flagcdn.com/w80/md.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Copenhagen',
    location: 'Copenhagen',
    countryCode: 'dk',
    flag: 'https://flagcdn.com/w80/dk.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Dublin',
    location: 'Dublin',
    countryCode: 'ie',
    flag: 'https://flagcdn.com/w80/ie.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Gibraltar',
    location: 'Gibraltar',
    countryCode: 'gi',
    flag: 'https://flagcdn.com/w80/gi.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Guernsey',
    location: 'Guernsey',
    countryCode: 'gg',
    flag: 'https://flagcdn.com/w80/gg.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Helsinki',
    location: 'Helsinki',
    countryCode: 'fi',
    flag: 'https://flagcdn.com/w80/fi.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Isle_of_Man',
    location: 'Isle of Man',
    countryCode: 'im',
    flag: 'https://flagcdn.com/w80/im.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Istanbul',
    location: 'Istanbul',
    countryCode: 'tr',
    flag: 'https://flagcdn.com/w80/tr.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Jersey',
    location: 'Jersey',
    countryCode: 'je',
    flag: 'https://flagcdn.com/w80/je.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Kaliningrad',
    location: 'Kaliningrad',
    countryCode: 'ru',
    flag: 'https://flagcdn.com/w80/ru.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Kiev',
    location: 'Kiev',
    countryCode: 'ua',
    flag: 'https://flagcdn.com/w80/ua.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Kirov',
    location: 'Kirov',
    countryCode: 'ru',
    flag: 'https://flagcdn.com/w80/ru.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Kyiv',
    location: 'Kyiv',
    countryCode: 'ua',
    flag: 'https://flagcdn.com/w80/ua.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Lisbon',
    location: 'Lisbon',
    countryCode: 'pt',
    flag: 'https://flagcdn.com/w80/pt.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Ljubljana',
    location: 'Ljubljana',
    countryCode: 'si',
    flag: 'https://flagcdn.com/w80/si.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/London',
    location: 'London',
    countryCode: 'gb',
    flag: 'https://flagcdn.com/w80/gb.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Luxembourg',
    location: 'Luxembourg',
    countryCode: 'lu',
    flag: 'https://flagcdn.com/w80/lu.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Madrid',
    location: 'Madrid',
    countryCode: 'es',
    flag: 'https://flagcdn.com/w80/es.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Malta',
    location: 'Malta',
    countryCode: 'mt',
    flag: 'https://flagcdn.com/w80/mt.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Mariehamn',
    location: 'Mariehamn',
    countryCode: 'fi',
    flag: 'https://flagcdn.com/w80/fi.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Minsk',
    location: 'Minsk',
    countryCode: 'by',
    flag: 'https://flagcdn.com/w80/by.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Monaco',
    location: 'Monaco',
    countryCode: 'mc',
    flag: 'https://flagcdn.com/w80/mc.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Moscow',
    location: 'Moscow',
    countryCode: 'ru',
    flag: 'https://flagcdn.com/w80/ru.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Nicosia',
    location: 'Nicosia',
    countryCode: 'cy',
    flag: 'https://flagcdn.com/w80/cy.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Oslo',
    location: 'Oslo',
    countryCode: 'no',
    flag: 'https://flagcdn.com/w80/no.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Paris',
    location: 'Paris',
    countryCode: 'fr',
    flag: 'https://flagcdn.com/w80/fr.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Podgorica',
    location: 'Podgorica',
    countryCode: 'rs',
    flag: 'https://flagcdn.com/w80/rs.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Prague',
    location: 'Prague',
    countryCode: 'cz',
    flag: 'https://flagcdn.com/w80/cz.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Riga',
    location: 'Riga',
    countryCode: 'lv',
    flag: 'https://flagcdn.com/w80/lv.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Rome',
    location: 'Rome',
    countryCode: 'it',
    flag: 'https://flagcdn.com/w80/it.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Samara',
    location: 'Samara',
    countryCode: 'ru',
    flag: 'https://flagcdn.com/w80/ru.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/San_Marino',
    location: 'San Marino',
    countryCode: 'it',
    flag: 'https://flagcdn.com/w80/it.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Sarajevo',
    location: 'Sarajevo',
    countryCode: 'ba',
    flag: 'https://flagcdn.com/w80/ba.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Saratov',
    location: 'Saratov',
    countryCode: 'ru',
    flag: 'https://flagcdn.com/w80/ru.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Simferopol',
    location: 'Simferopol',
    countryCode: 'ua',
    flag: 'https://flagcdn.com/w80/ua.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Skopje',
    location: 'Skopje',
    countryCode: 'mk',
    flag: 'https://flagcdn.com/w80/mk.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Sofia',
    location: 'Sofia',
    countryCode: 'bg',
    flag: 'https://flagcdn.com/w80/bg.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Stockholm',
    location: 'Stockholm',
    countryCode: 'se',
    flag: 'https://flagcdn.com/w80/se.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Tallinn',
    location: 'Tallinn',
    countryCode: 'ee',
    flag: 'https://flagcdn.com/w80/ee.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Tirane',
    location: 'Tirane',
    countryCode: 'al',
    flag: 'https://flagcdn.com/w80/al.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Tiraspol',
    location: 'Tiraspol',
    countryCode: 'md',
    flag: 'https://flagcdn.com/w80/md.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Ulyanovsk',
    location: 'Ulyanovsk',
    countryCode: 'ru',
    flag: 'https://flagcdn.com/w80/ru.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Uzhgorod',
    location: 'Uzhgorod',
    countryCode: 'ua',
    flag: 'https://flagcdn.com/w80/ua.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Vaduz',
    location: 'Vaduz',
    countryCode: 'li',
    flag: 'https://flagcdn.com/w80/li.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Vatican',
    location: 'Vatican',
    countryCode: 'it',
    flag: 'https://flagcdn.com/w80/it.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Vienna',
    location: 'Vienna',
    countryCode: 'at',
    flag: 'https://flagcdn.com/w80/at.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Vilnius',
    location: 'Vilnius',
    countryCode: 'lt',
    flag: 'https://flagcdn.com/w80/lt.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Volgograd',
    location: 'Volgograd',
    countryCode: 'ru',
    flag: 'https://flagcdn.com/w80/ru.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Warsaw',
    location: 'Warsaw',
    countryCode: 'pl',
    flag: 'https://flagcdn.com/w80/pl.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Zagreb',
    location: 'Zagreb',
    countryCode: 'hr',
    flag: 'https://flagcdn.com/w80/hr.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Zaporozhye',
    location: 'Zaporozhye',
    countryCode: 'ua',
    flag: 'https://flagcdn.com/w80/ua.png',
  ),
  TimeZoneItem(
    timezone: 'Europe/Zurich',
    location: 'Zurich',
    countryCode: 'ch',
    flag: 'https://flagcdn.com/w80/ch.png',
  ),
  TimeZoneItem(
    timezone: 'GB',
    location: 'GB',
    countryCode: 'gb',
    flag: 'https://flagcdn.com/w80/gb.png',
  ),
  TimeZoneItem(
    timezone: 'GB-Eire',
    location: 'GB-Eire',
    countryCode: 'gb',
    flag: 'https://flagcdn.com/w80/gb.png',
  ),
  TimeZoneItem(
    timezone: 'GMT',
    location: 'GMT',
    countryCode: '',
    flag: '',
  ),
  TimeZoneItem(
    timezone: 'GMT-0',
    location: 'GMT-0',
    countryCode: '',
    flag: '',
  ),
  TimeZoneItem(
    timezone: 'GMT+0',
    location: 'GMT+0',
    countryCode: '',
    flag: '',
  ),
  TimeZoneItem(
    timezone: 'GMT0',
    location: 'GMT0',
    countryCode: '',
    flag: '',
  ),
  TimeZoneItem(
    timezone: 'Greenwich',
    location: 'Greenwich',
    countryCode: '',
    flag: '',
  ),
  TimeZoneItem(
    timezone: 'Hongkong',
    location: 'Hongkong',
    countryCode: 'hk',
    flag: 'https://flagcdn.com/w80/hk.png',
  ),
  TimeZoneItem(
    timezone: 'HST',
    location: 'HST',
    countryCode: 'us',
    flag: 'https://flagcdn.com/w80/us.png',
  ),
  TimeZoneItem(
    timezone: 'Iceland',
    location: 'Iceland',
    countryCode: 'is',
    flag: 'https://flagcdn.com/w80/is.png',
  ),
  TimeZoneItem(
    timezone: 'Indian/Antananarivo',
    location: 'Antananarivo',
    countryCode: 'mg',
    flag: 'https://flagcdn.com/w80/mg.png',
  ),
  TimeZoneItem(
    timezone: 'Indian/Chagos',
    location: 'Chagos',
    countryCode: 'io',
    flag: 'https://flagcdn.com/w80/io.png',
  ),
  TimeZoneItem(
    timezone: 'Indian/Christmas',
    location: 'Christmas',
    countryCode: 'cx',
    flag: 'https://flagcdn.com/w80/cx.png',
  ),
  TimeZoneItem(
    timezone: 'Indian/Cocos',
    location: 'Cocos',
    countryCode: 'cc',
    flag: 'https://flagcdn.com/w80/cc.png',
  ),
  TimeZoneItem(
    timezone: 'Indian/Comoro',
    location: 'Comoro',
    countryCode: 'km',
    flag: 'https://flagcdn.com/w80/km.png',
  ),
  TimeZoneItem(
    timezone: 'Indian/Kerguelen',
    location: 'Kerguelen',
    countryCode: 'tf',
    flag: 'https://flagcdn.com/w80/tf.png',
  ),
  TimeZoneItem(
    timezone: 'Indian/Mahe',
    location: 'Mahe',
    countryCode: 'sc',
    flag: 'https://flagcdn.com/w80/sc.png',
  ),
  TimeZoneItem(
    timezone: 'Indian/Maldives',
    location: 'Maldives',
    countryCode: 'mv',
    flag: 'https://flagcdn.com/w80/mv.png',
  ),
  TimeZoneItem(
    timezone: 'Indian/Mauritius',
    location: 'Mauritius',
    countryCode: 'mu',
    flag: 'https://flagcdn.com/w80/mu.png',
  ),
  TimeZoneItem(
    timezone: 'Indian/Mayotte',
    location: 'Mayotte',
    countryCode: 'yt',
    flag: 'https://flagcdn.com/w80/yt.png',
  ),
  TimeZoneItem(
    timezone: 'Indian/Reunion',
    location: 'Reunion',
    countryCode: 're',
    flag: 'https://flagcdn.com/w80/re.png',
  ),
  TimeZoneItem(
    timezone: 'Iran',
    location: 'Iran',
    countryCode: 'ir',
    flag: 'https://flagcdn.com/w80/ir.png',
  ),
  TimeZoneItem(
    timezone: 'Israel',
    location: 'Israel',
    countryCode: 'il',
    flag: 'https://flagcdn.com/w80/il.png',
  ),
  TimeZoneItem(
    timezone: 'Jamaica',
    location: 'Jamaica',
    countryCode: 'jm',
    flag: 'https://flagcdn.com/w80/jm.png',
  ),
  TimeZoneItem(
    timezone: 'Japan',
    location: 'Japan',
    countryCode: 'jp',
    flag: 'https://flagcdn.com/w80/jp.png',
  ),
  TimeZoneItem(
    timezone: 'Kwajalein',
    location: 'Kwajalein',
    countryCode: 'mh',
    flag: 'https://flagcdn.com/w80/mh.png',
  ),
  TimeZoneItem(
    timezone: 'Libya',
    location: 'Libya',
    countryCode: 'ly',
    flag: 'https://flagcdn.com/w80/ly.png',
  ),
  TimeZoneItem(
    timezone: 'MET',
    location: 'MET',
    countryCode: 'be',
    flag: 'https://flagcdn.com/w80/be.png',
  ),
  TimeZoneItem(
    timezone: 'Mexico/BajaNorte',
    location: 'BajaNorte',
    countryCode: 'mx',
    flag: 'https://flagcdn.com/w80/mx.png',
  ),
  TimeZoneItem(
    timezone: 'Mexico/BajaSur',
    location: 'BajaSur',
    countryCode: 'mx',
    flag: 'https://flagcdn.com/w80/mx.png',
  ),
  TimeZoneItem(
    timezone: 'Mexico/General',
    location: 'General',
    countryCode: 'mx',
    flag: 'https://flagcdn.com/w80/mx.png',
  ),
  TimeZoneItem(
    timezone: 'MST',
    location: 'MST',
    countryCode: 'us',
    flag: 'https://flagcdn.com/w80/us.png',
  ),
  TimeZoneItem(
    timezone: 'MST7MDT',
    location: 'MST7MDT',
    countryCode: 'us',
    flag: 'https://flagcdn.com/w80/us.png',
  ),
  TimeZoneItem(
    timezone: 'Navajo',
    location: 'Navajo',
    countryCode: 'us',
    flag: 'https://flagcdn.com/w80/us.png',
  ),
  TimeZoneItem(
    timezone: 'NZ',
    location: 'NZ',
    countryCode: 'nz',
    flag: 'https://flagcdn.com/w80/nz.png',
  ),
  TimeZoneItem(
    timezone: 'NZ-CHAT',
    location: 'NZ-CHAT',
    countryCode: 'nz',
    flag: 'https://flagcdn.com/w80/nz.png',
  ),
  TimeZoneItem(
    timezone: 'Pacific/Apia',
    location: 'Apia',
    countryCode: 'ws',
    flag: 'https://flagcdn.com/w80/ws.png',
  ),
  TimeZoneItem(
    timezone: 'Pacific/Auckland',
    location: 'Auckland',
    countryCode: 'nz',
    flag: 'https://flagcdn.com/w80/nz.png',
  ),
  TimeZoneItem(
    timezone: 'Pacific/Bougainville',
    location: 'Bougainville',
    countryCode: 'pg',
    flag: 'https://flagcdn.com/w80/pg.png',
  ),
  TimeZoneItem(
    timezone: 'Pacific/Chatham',
    location: 'Chatham',
    countryCode: 'nz',
    flag: 'https://flagcdn.com/w80/nz.png',
  ),
  TimeZoneItem(
    timezone: 'Pacific/Chuuk',
    location: 'Chuuk',
    countryCode: 'fm',
    flag: 'https://flagcdn.com/w80/fm.png',
  ),
  TimeZoneItem(
    timezone: 'Pacific/Easter',
    location: 'Easter',
    countryCode: 'cl',
    flag: 'https://flagcdn.com/w80/cl.png',
  ),
  TimeZoneItem(
    timezone: 'Pacific/Efate',
    location: 'Efate',
    countryCode: 'vu',
    flag: 'https://flagcdn.com/w80/vu.png',
  ),
  TimeZoneItem(
    timezone: 'Pacific/Enderbury',
    location: 'Enderbury',
    countryCode: 'ki',
    flag: 'https://flagcdn.com/w80/ki.png',
  ),
  TimeZoneItem(
    timezone: 'Pacific/Fakaofo',
    location: 'Fakaofo',
    countryCode: 'tk',
    flag: 'https://flagcdn.com/w80/tk.png',
  ),
  TimeZoneItem(
    timezone: 'Pacific/Fiji',
    location: 'Fiji',
    countryCode: 'fj',
    flag: 'https://flagcdn.com/w80/fj.png',
  ),
  TimeZoneItem(
    timezone: 'Pacific/Funafuti',
    location: 'Funafuti',
    countryCode: 'tv',
    flag: 'https://flagcdn.com/w80/tv.png',
  ),
  TimeZoneItem(
    timezone: 'Pacific/Galapagos',
    location: 'Galapagos',
    countryCode: 'ec',
    flag: 'https://flagcdn.com/w80/ec.png',
  ),
  TimeZoneItem(
    timezone: 'Pacific/Gambier',
    location: 'Gambier',
    countryCode: 'pf',
    flag: 'https://flagcdn.com/w80/pf.png',
  ),
  TimeZoneItem(
    timezone: 'Pacific/Guadalcanal',
    location: 'Guadalcanal',
    countryCode: 'sb',
    flag: 'https://flagcdn.com/w80/sb.png',
  ),
  TimeZoneItem(
    timezone: 'Pacific/Guam',
    location: 'Guam',
    countryCode: 'gu',
    flag: 'https://flagcdn.com/w80/gu.png',
  ),
  TimeZoneItem(
    timezone: 'Pacific/Honolulu',
    location: 'Honolulu',
    countryCode: 'us',
    flag: 'https://flagcdn.com/w80/us.png',
  ),
  TimeZoneItem(
    timezone: 'Pacific/Johnston',
    location: 'Johnston',
    countryCode: 'us',
    flag: 'https://flagcdn.com/w80/us.png',
  ),
  TimeZoneItem(
    timezone: 'Pacific/Kanton',
    location: 'Kanton',
    countryCode: 'ki',
    flag: 'https://flagcdn.com/w80/ki.png',
  ),
  TimeZoneItem(
    timezone: 'Pacific/Kiritimati',
    location: 'Kiritimati',
    countryCode: 'ki',
    flag: 'https://flagcdn.com/w80/ki.png',
  ),
  TimeZoneItem(
    timezone: 'Pacific/Kosrae',
    location: 'Kosrae',
    countryCode: 'fm',
    flag: 'https://flagcdn.com/w80/fm.png',
  ),
  TimeZoneItem(
    timezone: 'Pacific/Kwajalein',
    location: 'Kwajalein',
    countryCode: 'mh',
    flag: 'https://flagcdn.com/w80/mh.png',
  ),
  TimeZoneItem(
    timezone: 'Pacific/Majuro',
    location: 'Majuro',
    countryCode: 'mh',
    flag: 'https://flagcdn.com/w80/mh.png',
  ),
  TimeZoneItem(
    timezone: 'Pacific/Marquesas',
    location: 'Marquesas',
    countryCode: 'pf',
    flag: 'https://flagcdn.com/w80/pf.png',
  ),
  TimeZoneItem(
    timezone: 'Pacific/Midway',
    location: 'Midway',
    countryCode: 'um',
    flag: 'https://flagcdn.com/w80/um.png',
  ),
  TimeZoneItem(
    timezone: 'Pacific/Nauru',
    location: 'Nauru',
    countryCode: 'nr',
    flag: 'https://flagcdn.com/w80/nr.png',
  ),
  TimeZoneItem(
    timezone: 'Pacific/Niue',
    location: 'Niue',
    countryCode: 'nu',
    flag: 'https://flagcdn.com/w80/nu.png',
  ),
  TimeZoneItem(
    timezone: 'Pacific/Norfolk',
    location: 'Norfolk',
    countryCode: 'nf',
    flag: 'https://flagcdn.com/w80/nf.png',
  ),
  TimeZoneItem(
    timezone: 'Pacific/Noumea',
    location: 'Noumea',
    countryCode: 'nc',
    flag: 'https://flagcdn.com/w80/nc.png',
  ),
  TimeZoneItem(
    timezone: 'Pacific/Pago_Pago',
    location: 'Pago Pago',
    countryCode: 'as',
    flag: 'https://flagcdn.com/w80/as.png',
  ),
  TimeZoneItem(
    timezone: 'Pacific/Palau',
    location: 'Palau',
    countryCode: 'pw',
    flag: 'https://flagcdn.com/w80/pw.png',
  ),
  TimeZoneItem(
    timezone: 'Pacific/Pitcairn',
    location: 'Pitcairn',
    countryCode: 'pn',
    flag: 'https://flagcdn.com/w80/pn.png',
  ),
  TimeZoneItem(
    timezone: 'Pacific/Pohnpei',
    location: 'Pohnpei',
    countryCode: 'fm',
    flag: 'https://flagcdn.com/w80/fm.png',
  ),
  TimeZoneItem(
    timezone: 'Pacific/Ponape',
    location: 'Ponape',
    countryCode: 'fm',
    flag: 'https://flagcdn.com/w80/fm.png',
  ),
  TimeZoneItem(
    timezone: 'Pacific/Port_Moresby',
    location: 'Port Moresby',
    countryCode: 'pg',
    flag: 'https://flagcdn.com/w80/pg.png',
  ),
  TimeZoneItem(
    timezone: 'Pacific/Rarotonga',
    location: 'Rarotonga',
    countryCode: 'ck',
    flag: 'https://flagcdn.com/w80/ck.png',
  ),
  TimeZoneItem(
    timezone: 'Pacific/Saipan',
    location: 'Saipan',
    countryCode: 'mp',
    flag: 'https://flagcdn.com/w80/mp.png',
  ),
  TimeZoneItem(
    timezone: 'Pacific/Samoa',
    location: 'Samoa',
    countryCode: 'as',
    flag: 'https://flagcdn.com/w80/as.png',
  ),
  TimeZoneItem(
    timezone: 'Pacific/Tahiti',
    location: 'Tahiti',
    countryCode: 'pf',
    flag: 'https://flagcdn.com/w80/pf.png',
  ),
  TimeZoneItem(
    timezone: 'Pacific/Tarawa',
    location: 'Tarawa',
    countryCode: 'ki',
    flag: 'https://flagcdn.com/w80/ki.png',
  ),
  TimeZoneItem(
    timezone: 'Pacific/Tongatapu',
    location: 'Tongatapu',
    countryCode: 'to',
    flag: 'https://flagcdn.com/w80/to.png',
  ),
  TimeZoneItem(
    timezone: 'Pacific/Truk',
    location: 'Truk',
    countryCode: 'fm',
    flag: 'https://flagcdn.com/w80/fm.png',
  ),
  TimeZoneItem(
    timezone: 'Pacific/Wake',
    location: 'Wake',
    countryCode: 'um',
    flag: 'https://flagcdn.com/w80/um.png',
  ),
  TimeZoneItem(
    timezone: 'Pacific/Wallis',
    location: 'Wallis',
    countryCode: 'wf',
    flag: 'https://flagcdn.com/w80/wf.png',
  ),
  TimeZoneItem(
    timezone: 'Pacific/Yap',
    location: 'Yap',
    countryCode: 'fm',
    flag: 'https://flagcdn.com/w80/fm.png',
  ),
  TimeZoneItem(
    timezone: 'Poland',
    location: 'Poland',
    countryCode: 'pl',
    flag: 'https://flagcdn.com/w80/pl.png',
  ),
  TimeZoneItem(
    timezone: 'Portugal',
    location: 'Portugal',
    countryCode: 'pt',
    flag: 'https://flagcdn.com/w80/pt.png',
  ),
  TimeZoneItem(
    timezone: 'PRC',
    location: 'PRC',
    countryCode: 'cn',
    flag: 'https://flagcdn.com/w80/cn.png',
  ),
  TimeZoneItem(
    timezone: 'PST8PDT',
    location: 'PST8PDT',
    countryCode: 'us',
    flag: 'https://flagcdn.com/w80/us.png',
  ),
  TimeZoneItem(
    timezone: 'ROC',
    location: 'ROC',
    countryCode: 'tw',
    flag: 'https://flagcdn.com/w80/tw.png',
  ),
  TimeZoneItem(
    timezone: 'ROK',
    location: 'ROK',
    countryCode: 'kr',
    flag: 'https://flagcdn.com/w80/kr.png',
  ),
  TimeZoneItem(
    timezone: 'Singapore',
    location: 'Singapore',
    countryCode: 'sg',
    flag: 'https://flagcdn.com/w80/sg.png',
  ),
  TimeZoneItem(
    timezone: 'Turkey',
    location: 'Turkey',
    countryCode: 'tr',
    flag: 'https://flagcdn.com/w80/tr.png',
  ),
  TimeZoneItem(
    timezone: 'UCT',
    location: 'UCT',
    countryCode: '',
    flag: '',
  ),
  TimeZoneItem(
    timezone: 'Universal',
    location: 'Universal',
    countryCode: '',
    flag: '',
  ),
  TimeZoneItem(
    timezone: 'US/Alaska',
    location: 'Alaska',
    countryCode: 'us',
    flag: 'https://flagcdn.com/w80/us.png',
  ),
  TimeZoneItem(
    timezone: 'US/Aleutian',
    location: 'Aleutian',
    countryCode: 'us',
    flag: 'https://flagcdn.com/w80/us.png',
  ),
  TimeZoneItem(
    timezone: 'US/Arizona',
    location: 'Arizona',
    countryCode: 'us',
    flag: 'https://flagcdn.com/w80/us.png',
  ),
  TimeZoneItem(
    timezone: 'US/Central',
    location: 'Central',
    countryCode: 'us',
    flag: 'https://flagcdn.com/w80/us.png',
  ),
  TimeZoneItem(
    timezone: 'US/East-Indiana',
    location: 'East-Indiana',
    countryCode: 'us',
    flag: 'https://flagcdn.com/w80/us.png',
  ),
  TimeZoneItem(
    timezone: 'US/Eastern',
    location: 'Eastern',
    countryCode: 'us',
    flag: 'https://flagcdn.com/w80/us.png',
  ),
  TimeZoneItem(
    timezone: 'US/Hawaii',
    location: 'Hawaii',
    countryCode: 'us',
    flag: 'https://flagcdn.com/w80/us.png',
  ),
  TimeZoneItem(
    timezone: 'US/Indiana-Starke',
    location: 'Indiana-Starke',
    countryCode: 'us',
    flag: 'https://flagcdn.com/w80/us.png',
  ),
  TimeZoneItem(
    timezone: 'US/Michigan',
    location: 'Michigan',
    countryCode: 'us',
    flag: 'https://flagcdn.com/w80/us.png',
  ),
  TimeZoneItem(
    timezone: 'US/Mountain',
    location: 'Mountain',
    countryCode: 'us',
    flag: 'https://flagcdn.com/w80/us.png',
  ),
  TimeZoneItem(
    timezone: 'US/Pacific',
    location: 'Pacific',
    countryCode: 'us',
    flag: 'https://flagcdn.com/w80/us.png',
  ),
  TimeZoneItem(
    timezone: 'US/Samoa',
    location: 'Samoa',
    countryCode: 'as',
    flag: 'https://flagcdn.com/w80/as.png',
  ),
  TimeZoneItem(
    timezone: 'UTC',
    location: 'UTC',
    countryCode: '',
    flag: '',
  ),
  TimeZoneItem(
    timezone: 'W-SU',
    location: 'W-SU',
    countryCode: 'ru',
    flag: 'https://flagcdn.com/w80/ru.png',
  ),
  TimeZoneItem(
    timezone: 'WET',
    location: 'WET',
    countryCode: 'pt',
    flag: 'https://flagcdn.com/w80/pt.png',
  ),
  TimeZoneItem(
    timezone: 'Zulu',
    location: 'Zulu',
    countryCode: '',
    flag: '',
  ),
];
